<cfset showForm = true>
<cfset counter = 0>
<cfif structKeyExists(form, "xlsfile") and len(form.xlsfile)>

<!--- Destination outside of web root --->

    <cffile action="upload" destination="#Application.CloudDirectory#" filefield="xlsfile" result="upload" nameconflict="makeunique">
    <cfif upload.fileWasSaved>
        <cfset theFile = upload.serverDirectory & "/" & upload.serverFile>
        <cfif right(theFile,3) eq 'xls'>
            <cfspreadsheet action="read" src="#theFile#" query="exceldata" headerrow="1">
            <cfset showForm = false>
        <cfelse>
            <cfset errors = "The file was not an Excel file.">
            <cffile action="delete" file="#theFile#">
        </cfif>
     <cfelse>
            <cfset errors="the file was not uploaded successfully">
    </cfif>
</cfif>

<cfif showForm>
    <cfif structKeyExists(variables, "errors")>
        <cfoutput>
            <p>
            <b style="text-align: center;">Error: #variables.errors#</b>
           </p>
        </cfoutput>
    </cfif>
    <form action="" enctype="multipart/form-data" method="post" style="margin-left: 300px">
        <div class="form-group">
            <label for=""> Upload Utility </label>
            <input id="upload-utility-4" class="file-loading" type="file"  name="xlsfile"  required>
        </div>
        <br>
        <div class="form-group">
            <input type="submit" class="btn btn-success" value="Upload XLS File">
        </div>
         </form>

<cfelse>


<cfif exceldata.recordCount is 1>
    <p>no recrod</p>
  <cfelse>

    <cfloop query="exceldata" startrow="2">

        <cfif isdefined('testzone')>
            <cfquery datasource="#application.dsn#" name="insertdata" result="insert">
          SET IDENTITY_INSERT TLU_Zones ON
          insert into TLU_Zones(ZONE,GRIDNUM,LAT_DD,LONG_DD,EASTING,NORTHING,SEGMENT,ZSEGMENT,ID)
          values(
                 <cfqueryparam value="#ZONE#" cfsqltype="cf_sql_varchar" null="#IIF(exceldata.zone EQ "", true, false)#">,
                 <cfqueryparam value="#GRIDNUM#" cfsqltype="cf_sql_float" null="#IIF(exceldata.GRIDNUM EQ "", true, false)#">,
                 <cfqueryparam value="#LAT_DD#" cfsqltype="cf_sql_float" null="#IIF(exceldata.LAT_DD EQ "", true, false)#">,
                 <cfqueryparam value="#LONG_DD#" cfsqltype="cf_sql_float" null="#IIF(exceldata.LONG_DD EQ "", true, false)#">,
                 <cfqueryparam value="#EASTING#" cfsqltype="cf_sql_float" null="#IIF(exceldata.EASTING EQ "", true, false)#">,
                 <cfqueryparam value="#NORTHING#" cfsqltype="cf_sql_float" null="#IIF(exceldata.NORTHING EQ "", true, false)#">,
                 <cfqueryparam value="#SEGMENT#" cfsqltype="cf_sql_varchar" null="#IIF(exceldata.SEGMENT EQ "", true, false)#">,
                 <cfqueryparam value="#ZSEGMENT#" cfsqltype="cf_sql_varchar" null="#IIF(exceldata.ZSEGMENT EQ "", true, false)#">,
                 <cfqueryparam value="#ID#" cfsqltype="cf_sql_integer">
               )
               SET IDENTITY_INSERT TLU_Zones OFF
        </cfquery>
        <cfelseif isdefined('Dolphin_table')>
            <cfquery datasource="#Application.dsn#" name="insertdolphin" result="insert">

          insert into test_Dolphin(

          [Recapture Date 2],Field1,[F Repro],[Source Sexed],[Recapture Date 1],[Recapture Date 3],Code,
          Name,Catalog,Sex,[Distinct],DistinctDate,FB_No,FB_On_Date,FB_Side,[LEFT],Media_Left,[RIGHT],Media_Right,
          [Biopsy No],PRES_LOBO,PRES_LOBO_DATE,Coalitions,[Lobo Confirmed],[Other Partners],Mothers,Lineage,[First YOY DOB EST],
          Grandmother,[Naming regime],[Family Name],[DOB ACT],[DOB EST],[Date of Death],[Field ID],[Dead?],YearOfBirth,
          SiteFide,[Dispersal Date],NeverSighted,Verified,UnableToVerify,DScore,[CFS ID],[Hubbs ID],[MJ ID],[JU ID],[FIT ID],
          [Source YOB],[HERA Error],[First Sighting Date],[Fin Change 1],[HERA/Rescue Fin Change 1],[Fin Change 2],[HERA/Rescue Fin Change 2],
          [Fin Change 3],[HERA/Rescue Fin Change 3],[Fin Change 4],[HERA/Rescue],[Pres Dead],GreatGrandmother,Verify,
          waterBody,bodyConditionCode,ageAtDeath,dorsalDecomposed,poorQualityPhoto,Unrecoveredo,momPushingDeadCalf,deadDorsalPhoto,bodyLenght,ageCohort,
          Details,otherAccessionNumbers,photoType,irlSegment,utmEsting,utmNorting,wMom,[Dispersal Date Source],ImageName
               )
          values(
                 <cfqueryparam value="#Recapture_Date_2#" cfsqltype="cf_sql_date" null="#IIF(exceldata.Recapture_Date_2 EQ "", true, false)#">,
                 <cfqueryparam value="#Field1#" cfsqltype="cf_sql_varchar" null="#IIF(exceldata.Field1 EQ "", true, false)#">,
                 <cfqueryparam value="#F_Repro#" cfsqltype="cf_sql_bit" null="#IIF(exceldata.F_Repro EQ "", true, false)#">,
                 <cfqueryparam value="#Source_Sexed#" cfsqltype="cf_sql_varchar" null="#IIF(exceldata.Source_Sexed EQ "", true, false)#">,
                 <cfqueryparam value="#Recapture_Date_1#" cfsqltype="cf_sql_date" null="#IIF(exceldata.Recapture_Date_1 EQ "", true, false)#">,
                 <cfqueryparam value="#Recapture_Date_3#" cfsqltype="cf_sql_date" null="#IIF(exceldata.Recapture_Date_3 EQ "", true, false)#">,
                 <cfqueryparam value="#Code#" cfsqltype="cf_sql_varchar" null="#IIF(exceldata.Code EQ "", true, false)#">,
                 <cfqueryparam value="#Name#" cfsqltype="cf_sql_varchar" null="#IIF(exceldata.Name EQ "", true, false)#">,
                 <cfqueryparam value="#Catalog#" cfsqltype="cf_sql_varchar" null="#IIF(exceldata.Catalog EQ "", true, false)#">,
                 <cfqueryparam value="#Sex#" cfsqltype="cf_sql_varchar" null="#IIF(exceldata.Sex EQ "", true, false)#">,
                 <cfqueryparam value="#Distinct#" cfsqltype="cf_sql_bit" null="#IIF(exceldata.Distinct EQ "", true, false)#">,
                 <cfqueryparam value="#DistinctDate#" cfsqltype="cf_sql_date" null="#IIF(exceldata.DistinctDate EQ "", true, false)#">,
                 <cfqueryparam value="#FB_No#" cfsqltype="cf_sql_varchar" null="#IIF(exceldata.FB_No EQ "", true, false)#">,
                 <cfqueryparam value="#FB_On_Date#" cfsqltype="cf_sql_date" null="#IIF(exceldata.FB_On_Date EQ "", true, false)#">,
                 <cfqueryparam value="#FB_Side#" cfsqltype="cf_sql_varchar" null="#IIF(exceldata.FB_Side EQ "", true, false)#">,
                 <cfqueryparam value="#LEFT#" cfsqltype="cf_sql_tinyint" null="#IIF(exceldata.LEFT EQ "", true, false)#">,
                 <cfqueryparam value="#Media_Left#" cfsqltype="cf_sql_varchar" null="#IIF(exceldata.Media_Left EQ "", true, false)#">,
                 <cfqueryparam value="#RIGHT#" cfsqltype="cf_sql_tinyint" null="#IIF(exceldata.Right EQ "", true, false)#">,
                 <cfqueryparam value="#Media_Right#" cfsqltype="cf_sql_varchar" null="#IIF(exceldata.Media_Right EQ "", true, false)#">,
                 <cfqueryparam value="#Biopsy_No#" cfsqltype="cf_sql_varchar" null="#IIF(exceldata.Biopsy_No EQ "", true, false)#">,
                 <cfqueryparam value="#PRES_LOBO#" cfsqltype="cf_sql_bit" null="#IIF(exceldata.PRES_LOBO EQ "", true, false)#">,
                 <cfqueryparam value="#PRES_LOBO_DATE#" cfsqltype="cf_sql_date" null="#IIF(exceldata.PRES_LOBO_DATE EQ "", true, false)#">,
                 <cfqueryparam value="#Coalitions#" cfsqltype="cf_sql_varchar" null="#IIF(exceldata.Coalitions EQ "", true, false)#">,
                 <cfqueryparam value="#Lobo_Confirmed#" cfsqltype="cf_sql_varchar" null="#IIF(exceldata.Lobo_Confirmed EQ "", true, false)#">,
                 <cfqueryparam value="#Other_Partners#" cfsqltype="cf_sql_varchar" null="#IIF(exceldata.Other_Partners EQ "", true, false)#">,
                 <cfqueryparam value="#Mothers#" cfsqltype="cf_sql_varchar" null="#IIF(exceldata.Mothers EQ "", true, false)#">,
                 <cfqueryparam value="#Lineage#" cfsqltype="cf_sql_varchar" null="#IIF(exceldata.Lineage EQ "", true, false)#">,
                 <cfqueryparam value="#First_YOY_DOB_EST#" cfsqltype="cf_sql_varchar" null="#IIF(exceldata.First_YOY_DOB_EST EQ "", true, false)#">,
                 <cfqueryparam value="#Grandmother#" cfsqltype="cf_sql_varchar" null="#IIF(exceldata.Grandmother EQ "", true, false)#">,
                 <cfqueryparam value="#Naming_regime#" cfsqltype="cf_sql_varchar" null="#IIF(exceldata.Naming_regime EQ "", true, false)#">,
                 <cfqueryparam value="#Family_Name#" cfsqltype="cf_sql_varchar" null="#IIF(exceldata.Family_Name EQ "", true, false)#">,
                 <cfqueryparam value="#DOB_ACT#" cfsqltype="cf_sql_varchar" null="#IIF(exceldata.DOB_ACT EQ "", true, false)#">,
                 <cfqueryparam value="#DOB_EST#" cfsqltype="cf_sql_varchar" null="#IIF(exceldata.DOB_EST EQ "", true, false)#">,
                 <cfqueryparam value="#Date_of_Death#" cfsqltype="cf_sql_date" null="#IIF(exceldata.Date_of_Death EQ "", true, false)#">,
                 <cfqueryparam value="#Field_ID#" cfsqltype="cf_sql_varchar" null="#IIF(exceldata.Field_ID EQ "", true, false)#">,
                 <cfqueryparam value="#Dead#" cfsqltype="cf_sql_bit" null="#IIF(exceldata.Dead EQ "", true, false)#">,
                 <cfqueryparam value="#YearOfBirth#" cfsqltype="cf_sql_varchar" null="#IIF(exceldata.YearOfBirth EQ "", true, false)#">,
                 <cfqueryparam value="#SiteFide#" cfsqltype="cf_sql_varchar" null="#IIF(exceldata.SiteFide EQ "", true, false)#">,
                 <cfqueryparam value="#Dispersal_Date#" cfsqltype="cf_sql_date" null="#IIF(exceldata.Dispersal_Date EQ "", true, false)#">,
                 <cfqueryparam value="#NeverSighted#" cfsqltype="cf_sql_bit" null="#IIF(exceldata.NeverSighted EQ "", true, false)#">,
                 <cfqueryparam value="#Verified#" cfsqltype="cf_sql_bit" null="#IIF(exceldata.Verified EQ "", true, false)#">,
                 <cfqueryparam value="#UnableToVerify#" cfsqltype="cf_sql_bit" null="#IIF(exceldata.UnableToVerify EQ "", true, false)#">,
                 <cfqueryparam value="#DScore#" cfsqltype="cf_sql_varchar" null="#IIF(exceldata.DScore EQ "", true, false)#">,
                 <cfqueryparam value="#CFS_ID#" cfsqltype="cf_sql_varchar" null="#IIF(exceldata.CFS_ID EQ "", true, false)#">,
                 <cfqueryparam value="#Hubbs_ID#" cfsqltype="cf_sql_varchar" null="#IIF(exceldata.Hubbs_ID EQ "", true, false)#">,
                 <cfqueryparam value="#MJ_ID#" cfsqltype="cf_sql_varchar" null="#IIF(exceldata.MJ_ID EQ "", true, false)#">,
                 <cfqueryparam value="#JU_ID#" cfsqltype="cf_sql_varchar" null="#IIF(exceldata.JU_ID EQ "", true, false)#">,
                 <cfqueryparam value="#FIT_ID#" cfsqltype="cf_sql_varchar" null="#IIF(exceldata.FIT_ID EQ "", true, false)#">,
                 <cfqueryparam value="#Source_YOB#" cfsqltype="cf_sql_integer" null="#IIF(exceldata.Source_YOB EQ "", true, false)#">,
                 <cfqueryparam value="#HERA_Error#" cfsqltype="cf_sql_varchar" null="#IIF(exceldata.HERA_Error EQ "", true, false)#">,
                 <cfqueryparam value="#First_Sighting_Date#" cfsqltype="cf_sql_date" null="#IIF(exceldata.First_Sighting_Date EQ "", true, false)#">,
                 <cfqueryparam value="#Fin_Change_1#" cfsqltype="cf_sql_date" null="#IIF(exceldata.Fin_Change_1 EQ "", true, false)#">,
                 <cfqueryparam value="#HERA_Rescue_Fin_Change_1#" cfsqltype="cf_sql_bit" null="#IIF(exceldata.HERA_Rescue_Fin_Change_1 EQ "", true, false)#">,
                 <cfqueryparam value="#Fin_Change_2#" cfsqltype="cf_sql_date" null="#IIF(exceldata.Fin_Change_2 EQ "", true, false)#">,
                 <cfqueryparam value="#HERA_Rescue_Fin_Change_2#" cfsqltype="cf_sql_bit" null="#IIF(exceldata.HERA_Rescue_Fin_Change_2 EQ "", true, false)#">,
                 <cfqueryparam value="#Fin_Change_3#" cfsqltype="cf_sql_date" null="#IIF(exceldata.Fin_Change_3 EQ "", true, false)#">,
                 <cfqueryparam value="#HERA_Rescue_Fin_Change_3#" cfsqltype="cf_sql_bit" null="#IIF(exceldata.HERA_Rescue_Fin_Change_3 EQ "", true, false)#">,
                 <cfqueryparam value="#Fin_Change_4#" cfsqltype="cf_sql_varchar" null="#IIF(exceldata.Fin_Change_4 EQ "", true, false)#">,
                 <cfqueryparam value="#HERA_Rescue#" cfsqltype="cf_sql_bit" null="#IIF(exceldata.HERA_Rescue EQ "", true, false)#">,
                 <cfqueryparam value="#Pres_Dead#" cfsqltype="cf_sql_bit" null="#IIF(exceldata.Pres_Dead EQ "", true, false)#">,
                 <cfqueryparam value="#GreatGrandmother#" cfsqltype="cf_sql_varchar" null="#IIF(exceldata.GreatGrandmother EQ "", true, false)#">,
                 <cfqueryparam value="#Verify#" cfsqltype="cf_sql_integer" null="#IIF(exceldata.Verify EQ "", true, false)#">,
                 <cfqueryparam value="#waterBody#" cfsqltype="cf_sql_varchar" null="#IIF(exceldata.waterBody EQ "", true, false)#">,
                 <cfqueryparam value="#bodyConditionCode#" cfsqltype="cf_sql_varchar" null="#IIF(exceldata.bodyConditionCode EQ "", true, false)#">,
                 <cfqueryparam value="#ageAtDeath#" cfsqltype="cf_sql_varchar" null="#IIF(exceldata.ageAtDeath EQ "", true, false)#">,
                 <cfqueryparam value="#dorsalDecomposed#" cfsqltype="cf_sql_varchar" null="#IIF(exceldata.dorsalDecomposed EQ "", true, false)#">,
                 <cfqueryparam value="#poorQualityPhoto#" cfsqltype="cf_sql_varchar" null="#IIF(exceldata.poorQualityPhoto EQ "", true, false)#">,
                 <cfqueryparam value="#Unrecoveredo#" cfsqltype="cf_sql_varchar" null="#IIF(exceldata.Unrecoveredo EQ "", true, false)#">,
                 <cfqueryparam value="#momPushingDeadCalf#" cfsqltype="cf_sql_varchar" null="#IIF(exceldata.momPushingDeadCalf EQ "", true, false)#">,
                 <cfqueryparam value="#deadDorsalPhoto#" cfsqltype="cf_sql_varchar" null="#IIF(exceldata.deadDorsalPhoto EQ "", true, false)#">,
                 <cfqueryparam value="#bodyLenght#" cfsqltype="cf_sql_varchar" null="#IIF(exceldata.bodyLenght EQ "", true, false)#">,
                 <cfqueryparam value="#ageCohort#" cfsqltype="cf_sql_varchar" null="#IIF(exceldata.ageCohort EQ "", true, false)#">,
                 <cfqueryparam value="#Details#" cfsqltype="cf_sql_varchar" null="#IIF(exceldata.Details EQ "", true, false)#">,
                 <cfqueryparam value="#otherAccessionNumbers#" cfsqltype="cf_sql_varchar" null="#IIF(exceldata.otherAccessionNumbers EQ "", true, false)#">,
                 <cfqueryparam value="#photoType#" cfsqltype="cf_sql_varchar" null="#IIF(exceldata.photoType EQ "", true, false)#">,
                 <cfqueryparam value="#irlSegment#" cfsqltype="cf_sql_varchar" null="#IIF(exceldata.irlSegment EQ "", true, false)#">,
                 <cfqueryparam value="#utmEsting#" cfsqltype="cf_sql_varchar" null="#IIF(exceldata.utmEsting EQ "", true, false)#">,
                 <cfqueryparam value="#utmNorting#" cfsqltype="cf_sql_varchar" null="#IIF(exceldata.utmNorting EQ "", true, false)#">,
                 <cfqueryparam value="#wMom#" cfsqltype="cf_sql_varchar" null="#IIF(exceldata.wMom EQ "", true, false)#">,
                 <cfqueryparam value="#Dispersal_Date_Source#" cfsqltype="cf_sql_varchar" null="#IIF(exceldata.Dispersal_Date_Source EQ "", true, false)#">,
                 <cfqueryparam value="#ImageName#" cfsqltype="cf_sql_varchar" null="#IIF(exceldata.ImageName EQ "", true, false)#">
                )

          </cfquery>
         <cfelseif isdefined("sighting_table")>
             <cfquery datasource="#Application.dsn#" name="insertsighting" result="insert">
               insert into testSIGHTINGS
                (
                 SightingNumber,Zone_id,Survey,Project_ID,StartTime,EndTime,Location,[Photo Coverage Grade],NumberOfBoats,
                 DistanceToClosestBoat,Easting_X,Northing_Y,Begin_LAT_H,Begin_LAT_M,Begin_LAT_S,Begin_LAT_Dec,End_LAT_H,End_LAT_M,
                 End_LAT_S,End_LAT_Dec,Begin_LON_H,Begin_LON_M,Begin_LON_S,Begin_LON_Dec,End_LON_H,End_LON_M,End_LON_S,End_LON_Dec,
                 ICW_Begin,ICW_End,FE_TotalDolphin_Min,FE_TotalDolphin_Max,FE_TotalDolphin_Best,FE_TotalCalves_Min,FE_TotalCalves_Max,
                 FE_TotalCalves_Best,FE_YoungOfYear_Min,FE_YoungOfYear_Max,FE_YoungOfYear_Best,Photo_TotalDolphins_PosID,Photo_TotalCalves_PosID,
                 Photo_YoungOfYear_PosID,Photo_TotalDolphins_MinNotIDed,Photo_TotalCalves_MinNotIDed,Photo_YoungOfYear_MinNotIDed,Photo_TotalDolphins_MaxNotIDed,
                 Photo_TotalCalves_MaxNotIDed,Photo_YoungOfYear_MaxNotIDed,Photo_TotalDolphins_RevisedMin,Photo_TotalCalves_RevisedMin,Photo_YoungOfYear_RevisedMin,
                 Photo_TotalDolphins_RevisedMax,Photo_TotalCalves_RevisedMax,Photo_YoungOfYear_RevisedMax,Photo_TotalDolphins_FinalBest,
                 Photo_TotalCalves_FinalBest,Photo_YoungOfYear_FinalBest,Depth,WaterTemp,Salinity,Heading,AssociateOrg,AssocBioData1,AssocBioData2,
                 AssocBioData3,WaveHeight,Beaufort,Glare,Sightability,Weather,Fisheries_None,Fisheries_RecTrolling,Fisheries_RecAnchored,
                 Fisheries_CrabTraps,Fisheries_CrabWork,Activity_Avoid_Boat,Activity_Mill,Activity_Feed,Activity_ProbFeed,Activity_Travel,
                 Activity_Play,Activity_Rest,Activity_Leap_tailslap_chuff,Activity_Social,Activity_WithBoat,Activity_Other,Photo_Grade,
                 Photo_Analysis,Photo_Analysis_Final,Date_Entered,SDO_Initial,SDO_Final,[Data Initial],[Data Final],Body_Condition_Initial,
                 Body_Condition_Final,ARCVIEW_Initial,Notes,Total_Takes_A,Total_Takes_B,Zone,Takes,Herding,Depredation,Driver,Photographer,
                 analyzed,EastingInit_X,NorthingInit_Y,EastingEnd_X,NorthingEnd_Y,InitDDLAT_X,InitDDLONG_Y,EndDDLAT_X,EndDDLONG_Y,HeadingGen,
                 HeadingInit,HeadingFinal,GlareDirection,SalinityPPT,AirTemp,Conductivity,DepthFT,WindsSpeed,TideDirection,TideHeight,WindDirection,
                 Habitat,Activity_Herding,Activity_Depre,EnteredBy
                 )
               values(
               <cfqueryparam value='#SightingNumber#' cfsqltype="cf_sql_integer" null='#IIF(exceldata.SightingNumber EQ "", true, false)#'>,
               <cfqueryparam value='#Zone_id#' cfsqltype="cf_sql_integer" null='#IIF(exceldata.Zone_id EQ "", true, false)#'>,
               <cfqueryparam value='#Survey#' cfsqltype="cf_sql_varchar" null='#IIF(exceldata.Survey EQ "", true, false)#'>,
               <cfqueryparam value='#Project_ID#' cfsqltype="cf_sql_integer" null='#IIF(exceldata.Project_ID EQ "", true, false)#'>,
               <cfqueryparam value='#StartTime#' cfsqltype="cf_sql_timestamp" null='#IIF(exceldata.StartTime EQ "", true, false)#'>,
               <cfqueryparam value='#EndTime#' cfsqltype="cf_sql_timestamp" null='#IIF(exceldata.EndTime EQ "", true, false)#'>,
               <cfqueryparam value='#Location#' cfsqltype="cf_sql_varchar" null='#IIF(exceldata.Location EQ "", true, false)#'>,
               <cfqueryparam value='#Photo_Coverage_Grade#' cfsqltype="cf_sql_smallint" null='#IIF(exceldata.Photo_Coverage_Grade EQ "", true, false)#'>,
               <cfqueryparam value='#NumberOfBoats#' cfsqltype="cf_sql_smallint" null='#IIF(exceldata.NumberOfBoats EQ "", true, false)#'>,
               <cfqueryparam value='#DistanceToClosestBoat#' cfsqltype="cf_sql_smallint" null='#IIF(exceldata.DistanceToClosestBoat EQ "", true, false)#'>,
               <cfqueryparam value='#Easting_X#' cfsqltype="cf_sql_float" null='#IIF(exceldata.Easting_X EQ "", true, false)#'>,
               <cfqueryparam value='#Northing_Y#' cfsqltype="cf_sql_float" null='#IIF(exceldata.Northing_Y EQ "", true, false)#'>,
               <cfqueryparam value='#Begin_LAT_H#' cfsqltype="cf_sql_float" null='#IIF(exceldata.Begin_LAT_H EQ "", true, false)#'>,
               <cfqueryparam value='#Begin_LAT_M#' cfsqltype="cf_sql_smallint" null='#IIF(exceldata.Begin_LAT_M EQ "", true, false)#'>,
               <cfqueryparam value='#Begin_LAT_S#' cfsqltype="cf_sql_smallint" null='#IIF(exceldata.Begin_LAT_S EQ "", true, false)#'>,
               <cfqueryparam value='#Begin_LAT_Dec#' cfsqltype="cf_sql_float" null='#IIF(exceldata.Begin_LAT_Dec EQ "", true, false)#'>,
               <cfqueryparam value='#End_LAT_H#' cfsqltype="cf_sql_float" null='#IIF(exceldata.End_LAT_H EQ "", true, false)#'>,
               <cfqueryparam value='#End_LAT_M#' cfsqltype="cf_sql_smallint" null='#IIF(exceldata.End_LAT_M EQ "", true, false)#'>,
               <cfqueryparam value='#End_LAT_S#' cfsqltype="cf_sql_smallint" null='#IIF(exceldata.End_LAT_S EQ "", true, false)#'>,
               <cfqueryparam value='#End_LAT_Dec#' cfsqltype="cf_sql_float" null='#IIF(exceldata.End_LAT_Dec EQ "", true, false)#'>,
               <cfqueryparam value='#Begin_LON_H#' cfsqltype="cf_sql_float" null='#IIF(exceldata.Begin_LON_H EQ "", true, false)#'>,
               <cfqueryparam value='#Begin_LON_M#' cfsqltype="cf_sql_smallint" null='#IIF(exceldata.Begin_LON_M EQ "", true, false)#'>,
               <cfqueryparam value='#Begin_LON_S#' cfsqltype="cf_sql_smallint" null='#IIF(exceldata.Begin_LON_S EQ "", true, false)#'>,
               <cfqueryparam value='#Begin_LON_Dec#' cfsqltype="cf_sql_float" null='#IIF(exceldata.Begin_LON_Dec EQ "", true, false)#'>,
               <cfqueryparam value='#End_LON_H#' cfsqltype="cf_sql_float" null='#IIF(exceldata.End_LON_H EQ "", true, false)#'>,
               <cfqueryparam value='#End_LON_M#' cfsqltype="cf_sql_smallint" null='#IIF(exceldata.End_LON_M EQ "", true, false)#'>,
               <cfqueryparam value='#End_LON_S#' cfsqltype="cf_sql_smallint" null='#IIF(exceldata.End_LON_S EQ "", true, false)#'>,
               <cfqueryparam value='#End_LON_Dec#' cfsqltype="cf_sql_float" null='#IIF(exceldata.End_LON_Dec EQ "", true, false)#'>,
               <cfqueryparam value='#ICW_Begin#' cfsqltype="cf_sql_varchar" null='#IIF(exceldata.ICW_Begin EQ "", true, false)#'>,
               <cfqueryparam value='#ICW_End#' cfsqltype="cf_sql_varchar" null='#IIF(exceldata.ICW_End EQ "", true, false)#'>,
               <cfqueryparam value='#FE_TotalDolphin_Min#' cfsqltype="cf_sql_integer" null='#IIF(exceldata.FE_TotalDolphin_Min EQ "", true, false)#'>,
               <cfqueryparam value='#FE_TotalDolphin_Max#' cfsqltype="cf_sql_integer" null='#IIF(exceldata.FE_TotalDolphin_Max EQ "", true, false)#'>,
               <cfqueryparam value='#FE_TotalDolphin_Best#' cfsqltype="cf_sql_integer" null='#IIF(exceldata.FE_TotalDolphin_Best EQ "", true, false)#'>,
               <cfqueryparam value='#FE_TotalCalves_Min#' cfsqltype="cf_sql_integer" null='#IIF(exceldata.FE_TotalCalves_Min EQ "", true, false)#'>,
               <cfqueryparam value='#FE_TotalCalves_Max#' cfsqltype="cf_sql_integer" null='#IIF(exceldata.FE_TotalCalves_Max EQ "", true, false)#'>,
               <cfqueryparam value='#FE_TotalCalves_Best#' cfsqltype="cf_sql_integer" null='#IIF(exceldata.FE_TotalCalves_Best EQ "", true, false)#'>,
               <cfqueryparam value='#FE_YoungOfYear_Min#' cfsqltype="cf_sql_integer" null='#IIF(exceldata.FE_YoungOfYear_Min EQ "", true, false)#'>,
               <cfqueryparam value='#FE_YoungOfYear_Max#' cfsqltype="cf_sql_integer" null='#IIF(exceldata.FE_YoungOfYear_Max EQ "", true, false)#'>,
               <cfqueryparam value='#FE_YoungOfYear_Best#' cfsqltype="cf_sql_integer" null='#IIF(exceldata.FE_YoungOfYear_Best EQ "", true, false)#'>,
               <cfqueryparam value='#Photo_TotalDolphins_PosID#' cfsqltype="cf_sql_tinyint" null='#IIF(exceldata.Photo_TotalDolphins_PosID EQ "", true, false)#'>,
               <cfqueryparam value='#Photo_TotalCalves_PosID#' cfsqltype="cf_sql_tinyint" null='#IIF(exceldata.Photo_TotalCalves_PosID EQ "", true, false)#'>,
               <cfqueryparam value='#Photo_YoungOfYear_PosID#' cfsqltype="cf_sql_tinyint" null='#IIF(exceldata.Photo_YoungOfYear_PosID EQ "", true, false)#'>,
               <cfqueryparam value='#Photo_TotalDolphins_MinNotIDed#' cfsqltype="cf_sql_tinyint" null='#IIF(exceldata.Photo_TotalDolphins_MinNotIDed EQ "", true, false)#'>,
               <cfqueryparam value='#Photo_TotalCalves_MinNotIDed#' cfsqltype="cf_sql_tinyint" null='#IIF(exceldata.Photo_TotalCalves_MinNotIDed EQ "", true, false)#'>,
               <cfqueryparam value='#Photo_YoungOfYear_MinNotIDed#' cfsqltype="cf_sql_tinyint" null='#IIF(exceldata.Photo_YoungOfYear_MinNotIDed EQ "", true, false)#'>,
               <cfqueryparam value='#Photo_TotalDolphins_MaxNotIDed#' cfsqltype="cf_sql_tinyint" null='#IIF(exceldata.Photo_TotalDolphins_MaxNotIDed EQ "", true, false)#'>,
               <cfqueryparam value='#Photo_TotalCalves_MaxNotIDed#' cfsqltype="cf_sql_tinyint" null='#IIF(exceldata.Photo_TotalCalves_MaxNotIDed EQ "", true, false)#'>,
               <cfqueryparam value='#Photo_YoungOfYear_MaxNotIDed#' cfsqltype="cf_sql_tinyint" null='#IIF(exceldata.Photo_YoungOfYear_MaxNotIDed EQ "", true, false)#'>,
               <cfqueryparam value='#Photo_TotalDolphins_RevisedMin#' cfsqltype="cf_sql_tinyint" null='#IIF(exceldata.Photo_TotalDolphins_RevisedMin EQ "", true, false)#'>,
               <cfqueryparam value='#Photo_TotalCalves_RevisedMin#' cfsqltype="cf_sql_tinyint" null='#IIF(exceldata.Photo_TotalCalves_RevisedMin EQ "", true, false)#'>,
               <cfqueryparam value='#Photo_YoungOfYear_RevisedMin#' cfsqltype="cf_sql_tinyint" null='#IIF(exceldata.Photo_YoungOfYear_RevisedMin EQ "", true, false)#'>,
               <cfqueryparam value='#Photo_TotalDolphins_RevisedMax#' cfsqltype="cf_sql_tinyint" null='#IIF(exceldata.Photo_TotalDolphins_RevisedMax EQ "", true, false)#'>,
               <cfqueryparam value='#Photo_TotalCalves_RevisedMax#' cfsqltype="cf_sql_tinyint" null='#IIF(exceldata.Photo_TotalCalves_RevisedMax EQ "", true, false)#'>,
               <cfqueryparam value='#Photo_YoungOfYear_RevisedMax#' cfsqltype="cf_sql_tinyint" null='#IIF(exceldata.Photo_YoungOfYear_RevisedMax EQ "", true, false)#'>,
               <cfqueryparam value='#Photo_TotalDolphins_FinalBest#' cfsqltype="cf_sql_tinyint" null='#IIF(exceldata.Photo_TotalDolphins_FinalBest EQ "", true, false)#'>,
               <cfqueryparam value='#Photo_TotalCalves_FinalBest#' cfsqltype="cf_sql_tinyint" null='#IIF(exceldata.Photo_TotalCalves_FinalBest EQ "", true, false)#'>,
               <cfqueryparam value='#Photo_YoungOfYear_FinalBest#' cfsqltype="cf_sql_tinyint" null='#IIF(exceldata.Photo_YoungOfYear_FinalBest EQ "", true, false)#'>,
               <cfqueryparam value='#Depth#' cfsqltype="cf_sql_integer" null='#IIF(exceldata.Depth EQ "", true, false)#'>,
               <cfqueryparam value='#WaterTemp#' cfsqltype="cf_sql_integer" null='#IIF(exceldata.WaterTemp EQ "", true, false)#'>,
               <cfqueryparam value='#Salinity#' cfsqltype="cf_sql_integer" null='#IIF(exceldata.Salinity EQ "", true, false)#'>,
               <cfqueryparam value='#Heading#' cfsqltype="cf_sql_varchar" null='#IIF(exceldata.Heading EQ "", true, false)#'>,
               <cfqueryparam value='#AssociateOrg#' cfsqltype="cf_sql_varchar" null='#IIF(exceldata.AssociateOrg EQ "", true, false)#'>,
               <cfqueryparam value='#AssocBioData1#' cfsqltype="cf_sql_integer" null='#IIF(exceldata.AssocBioData1 EQ "", true, false)#'>,
               <cfqueryparam value='#AssocBioData2#' cfsqltype="cf_sql_integer" null='#IIF(exceldata.AssocBioData2 EQ "", true, false)#'>,
               <cfqueryparam value='#AssocBioData3#' cfsqltype="cf_sql_integer" null='#IIF(exceldata.AssocBioData3 EQ "", true, false)#'>,
               <cfqueryparam value='#WaveHeight#' cfsqltype="cf_sql_integer" null='#IIF(exceldata.WaveHeight EQ "", true, false)#'>,
               <cfqueryparam value='#Beaufort#' cfsqltype="cf_sql_integer" null='#IIF(exceldata.Beaufort EQ "", true, false)#'>,
               <cfqueryparam value='#Glare#' cfsqltype="cf_sql_integer" null='#IIF(exceldata.Glare EQ "", true, false)#'>,
               <cfqueryparam value='#Sightability#' cfsqltype="cf_sql_integer" null='#IIF(exceldata.Sightability EQ "", true, false)#'>,
               <cfqueryparam value='#Weather#' cfsqltype="cf_sql_integer" null='#IIF(exceldata.Weather EQ "", true, false)#'>,
               <cfqueryparam value='#Fisheries_None#' cfsqltype="cf_sql_bit" null='#IIF(exceldata.Fisheries_None EQ "", true, false)#'>,
               <cfqueryparam value='#Fisheries_RecTrolling#' cfsqltype="cf_sql_bit" null='#IIF(exceldata.Fisheries_RecTrolling EQ "", true, false)#'>,
               <cfqueryparam value='#Fisheries_RecAnchored#' cfsqltype="cf_sql_bit" null='#IIF(exceldata.Fisheries_RecAnchored EQ "", true, false)#'>,
               <cfqueryparam value='#Fisheries_CrabTraps#' cfsqltype="cf_sql_bit" null='#IIF(exceldata.Fisheries_CrabTraps EQ "", true, false)#'>,
               <cfqueryparam value='#Fisheries_CrabWork#' cfsqltype="cf_sql_bit" null='#IIF(exceldata.Fisheries_CrabWork EQ "", true, false)#'>,
               <cfqueryparam value='#Activity_Avoid_Boat#' cfsqltype="cf_sql_tinyint" null='#IIF(exceldata.Activity_Avoid_Boat EQ "", true, false)#'>,
               <cfqueryparam value='#Activity_Mill#' cfsqltype="cf_sql_tinyint" null='#IIF(exceldata.Activity_Mill EQ "", true, false)#'>,
               <cfqueryparam value='#Activity_Feed#' cfsqltype="cf_sql_tinyint" null='#IIF(exceldata.Activity_Feed EQ "", true, false)#'>,
               <cfqueryparam value='#Activity_ProbFeed#' cfsqltype="cf_sql_integer" null='#IIF(exceldata.Activity_ProbFeed EQ "", true, false)#'>,
               <cfqueryparam value='#Activity_Travel#' cfsqltype="cf_sql_tinyint" null='#IIF(exceldata.Activity_Travel  EQ "", true, false)#'>,
               <cfqueryparam value='#Activity_Play#' cfsqltype="cf_sql_tinyint" null='#IIF(exceldata.Activity_Play  EQ "", true, false)#'>,
               <cfqueryparam value='#Activity_Rest#' cfsqltype="cf_sql_tinyint" null='#IIF(exceldata.Activity_Rest  EQ "", true, false)#'>,
               <cfqueryparam value='#Activity_Leap_tailslap_chuff#' cfsqltype="cf_sql_tinyint" null='#IIF(exceldata.Activity_Leap_tailslap_chuff  EQ "", true, false)#'>,
               <cfqueryparam value='#Activity_Social#' cfsqltype="cf_sql_tinyint" null='#IIF(exceldata.Activity_Social  EQ "", true, false)#'>,
               <cfqueryparam value='#Activity_WithBoat#' cfsqltype="cf_sql_tinyint" null='#IIF(exceldata.Activity_WithBoat  EQ "", true, false)#'>,
               <cfqueryparam value='#Activity_Other#' cfsqltype="cf_sql_tinyint" null='#IIF(exceldata.Activity_Other  EQ "", true, false)#'>,
               <cfqueryparam value='#Photo_Grade#' cfsqltype="cf_sql_tinyint" null='#IIF(exceldata.Photo_Grade  EQ "", true, false)#'>,
               <cfqueryparam value='#Photo_Analysis#' cfsqltype="cf_sql_varchar" null='#IIF(exceldata.Photo_Analysis  EQ "", true, false)#'>,
               <cfqueryparam value='#Photo_Analysis_Final#' cfsqltype="cf_sql_varchar" null='#IIF(exceldata.Photo_Analysis_Final  EQ "", true, false)#'>,
               <cfqueryparam value='#Date_Entered#' cfsqltype="cf_sql_timestamp" null='#IIF(exceldata.Date_Entered  EQ "", true, false)#'>,
               <cfqueryparam value='#SDO_Initial#' cfsqltype="cf_sql_varchar" null='#IIF(exceldata.SDO_Initial  EQ "", true, false)#'>,
               <cfqueryparam value='#SDO_Final#' cfsqltype="cf_sql_varchar" null='#IIF(exceldata.SDO_Final  EQ "", true, false)#'>,
               <cfqueryparam value='#Data_Initial#' cfsqltype="cf_sql_varchar" null='#IIF(exceldata.Data_Initial  EQ "", true, false)#'>,
               <cfqueryparam value='#Data_Final#' cfsqltype="cf_sql_varchar" null='#IIF(exceldata.Data_Final  EQ "", true, false)#'>,
               <cfqueryparam value='#Body_Condition_Initial#' cfsqltype="cf_sql_varchar" null='#IIF(exceldata.Body_Condition_Initial  EQ "", true, false)#'>,
               <cfqueryparam value='#Body_Condition_Final#' cfsqltype="cf_sql_varchar" null='#IIF(exceldata.Body_Condition_Final   EQ "", true, false)#'>,
               <cfqueryparam value='#ARCVIEW_Initial#' cfsqltype="cf_sql_varchar" null='#IIF(exceldata.ARCVIEW_Initial   EQ "", true, false)#'>,
               <cfqueryparam value='#Notes#' cfsqltype="cf_sql_varchar" null='#IIF(exceldata.Notes   EQ "", true, false)#'>,
               <cfqueryparam value='#Total_Takes_A#' cfsqltype="cf_sql_integer" null='#IIF(exceldata.Total_Takes_A   EQ "", true, false)#'>,
               <cfqueryparam value='#Total_Takes_B#' cfsqltype="cf_sql_integer" null='#IIF(exceldata.Total_Takes_B   EQ "", true, false)#'>,
               <cfqueryparam value='#Zone#' cfsqltype="cf_sql_varchar" null='#IIF(exceldata.Zone   EQ "", true, false)#'>,
               <cfqueryparam value='#Takes#' cfsqltype="cf_sql_varchar" null='#IIF(exceldata.Takes   EQ "", true, false)#'>,
               <cfqueryparam value='#Herding#' cfsqltype="cf_sql_integer" null='#IIF(exceldata.Herding   EQ "", true, false)#'>,
               <cfqueryparam value='#Depredation#' cfsqltype="cf_sql_integer" null='#IIF(exceldata.Depredation   EQ "", true, false)#'>,
               <cfqueryparam value='#Driver#' cfsqltype="cf_sql_integer" null='#IIF(exceldata.Driver   EQ "", true, false)#'>,
               <cfqueryparam value='#Photographer#' cfsqltype="cf_sql_integer" null='#IIF(exceldata.Photographer   EQ "", true, false)#'>,
               <cfqueryparam value='#analyzed#' cfsqltype="cf_sql_integer" null='#IIF(exceldata.analyzed   EQ "", true, false)#'>,
               <cfqueryparam value='#EastingInit_X#' cfsqltype="cf_sql_float" null='#IIF(exceldata.EastingInit_X   EQ "", true, false)#'>,
               <cfqueryparam value='#NorthingInit_Y#' cfsqltype="cf_sql_float" null='#IIF(exceldata.NorthingInit_Y   EQ "", true, false)#'>,
               <cfqueryparam value='#EastingEnd_X#' cfsqltype="cf_sql_float" null='#IIF(exceldata.EastingEnd_X   EQ "", true, false)#'>,
               <cfqueryparam value='#NorthingEnd_Y#' cfsqltype="cf_sql_float" null='#IIF(exceldata.NorthingEnd_Y   EQ "", true, false)#'>,
               <cfqueryparam value='#InitDDLAT_X#' cfsqltype="cf_sql_float" null='#IIF(exceldata.InitDDLAT_X   EQ "", true, false)#'>,
               <cfqueryparam value='#InitDDLONG_Y#' cfsqltype="cf_sql_float" null='#IIF(exceldata.InitDDLONG_Y   EQ "", true, false)#'>,
               <cfqueryparam value='#EndDDLAT_X#' cfsqltype="cf_sql_float" null='#IIF(exceldata.EndDDLAT_X   EQ "", true, false)#'>,
               <cfqueryparam value='#EndDDLONG_Y#' cfsqltype="cf_sql_float" null='#IIF(exceldata.EndDDLONG_Y   EQ "", true, false)#'>,
               <cfqueryparam value='#HeadingGen#' cfsqltype="cf_sql_varchar" null='#IIF(exceldata.HeadingGen   EQ "", true, false)#'>,
               <cfqueryparam value='#HeadingInit#' cfsqltype="cf_sql_varchar" null='#IIF(exceldata.HeadingInit   EQ "", true, false)#'>,
               <cfqueryparam value='#HeadingFinal#' cfsqltype="cf_sql_varchar" null='#IIF(exceldata.HeadingFinal   EQ "", true, false)#'>,
               <cfqueryparam value='#GlareDirection#' cfsqltype="cf_sql_varchar" null='#IIF(exceldata.GlareDirection   EQ "", true, false)#'>,
               <cfqueryparam value='#SalinityPPT#' cfsqltype="cf_sql_float" null='#IIF(exceldata.SalinityPPT   EQ "", true, false)#'>,
               <cfqueryparam value='#AirTemp#' cfsqltype="cf_sql_float" null='#IIF(exceldata.AirTemp   EQ "", true, false)#'>,
               <cfqueryparam value='#Conductivity#' cfsqltype="cf_sql_float" null='#IIF(exceldata.Conductivity   EQ "", true, false)#'>,
               <cfqueryparam value='#DepthFT#' cfsqltype="cf_sql_float" null='#IIF(exceldata.DepthFT   EQ "", true, false)#'>,
               <cfqueryparam value='#WindsSpeed#' cfsqltype="cf_sql_float" null='#IIF(exceldata.WindsSpeed   EQ "", true, false)#'>,
               <cfqueryparam value='#TideDirection#' cfsqltype="cf_sql_varchar" null='#IIF(exceldata.TideDirection   EQ "", true, false)#'>,
               <cfqueryparam value='#TideHeight#' cfsqltype="cf_sql_varchar" null='#IIF(exceldata.TideHeight   EQ "", true, false)#'>,
               <cfqueryparam value='#WindDirection#' cfsqltype="cf_sql_integer" null='#IIF(exceldata.WindDirection   EQ "", true, false)#'>,
               <cfqueryparam value='#Habitat#' cfsqltype="cf_sql_varchar" null='#IIF(exceldata.Habitat   EQ "", true, false)#'>,
               <cfqueryparam value='#Activity_Herding#' cfsqltype="cf_sql_tinyint" null='#IIF(exceldata.Activity_Herding   EQ "", true, false)#'>,
               <cfqueryparam value='#Activity_Depre#' cfsqltype="cf_sql_tinyint" null='#IIF(exceldata.Activity_Depre   EQ "", true, false)#'>,
               <cfqueryparam value='#EnteredBy#' cfsqltype="cf_sql_varchar" null='#IIF(exceldata.EnteredBy   EQ "", true, false)#'>
              )
               </cfquery>
            <cfelseif isdefined("test_projects")>

                <cfquery datasource="#Application.dsn#" name="insertproject" result="insert">
                    insert into test_projects(
                    Date,SurveyStartTime,SurveyEndTime,StartTime,EndTime,[Historical Survey Time],Platform,ResearchTeam,
                    Squad,SurveyArea,TotalDistance,SurveyDistance,BeginZoneID,EndZoneID,SurveyType,BR_BeginZoneID,
                    BR_EndZoneID,IR_BeginZoneID,IR_EndZoneID,ML_BeginZoneID,ML_EndZoneID,SLP_BeginZoneID,SLP_EndZoneID,ATL_BeginZoneID,
                    ATL_EndZoneID,EnteredBy,Stock,Summary,SubType,Type,Route,tempntbid
                    )
                    values(
                          <cfqueryparam cfsqltype="cf_sql_timestamp" value="#Date#">,
                          <cfqueryparam cfsqltype="cf_sql_timestamp" value="#SurveyStartTime#" null='#IIF(exceldata.SurveyStartTime   EQ "", true, false)#'>,
                          <cfqueryparam cfsqltype="cf_sql_timestamp" value="#SurveyEndTime#" null='#IIF(exceldata.SurveyEndTime   EQ "", true, false)#'>,
                          <cfqueryparam cfsqltype="cf_sql_timestamp" value="#StartTime#" null='#IIF(exceldata.StartTime   EQ "", true, false)#'>,
                          <cfqueryparam cfsqltype="cf_sql_timestamp" value="#EndTime#" null='#IIF(exceldata.EndTime   EQ "", true, false)#'>,
                          1,
                          <cfqueryparam value='#Platform#' cfsqltype="cf_sql_varchar" null='#IIF(exceldata.Platform   EQ "", true, false)#'>,
                          <cfqueryparam value='#ResearchTeam#' cfsqltype="cf_sql_varchar" null='#IIF(exceldata.ResearchTeam   EQ "", true, false)#'>,
                          <cfqueryparam value='#Squad#' cfsqltype="cf_sql_varchar" null='#IIF(exceldata.Squad   EQ "", true, false)#'>,
                          <cfqueryparam value='#SurveyArea#' cfsqltype="cf_sql_varchar" null='#IIF(exceldata.SurveyArea   EQ "", true, false)#'>,
                          <cfqueryparam value='#TotalDistance#' cfsqltype="cf_sql_float" null='#IIF(exceldata.TotalDistance   EQ "", true, false)#'>,
                          <cfqueryparam value='#SurveyDistance#' cfsqltype="cf_sql_float" null='#IIF(exceldata.SurveyDistance   EQ "", true, false)#'>,
                          <cfqueryparam value='#BeginZoneID#' cfsqltype="cf_sql_integer" null='#IIF(exceldata.BeginZoneID   EQ "", true, false)#'>,
                          <cfqueryparam value='#EndZoneID#' cfsqltype="cf_sql_integer" null='#IIF(exceldata.EndZoneID   EQ "", true, false)#'>,
                          <cfqueryparam value='#SurveyType#' cfsqltype="cf_sql_integer" null='#IIF(exceldata.SurveyType   EQ "", true, false)#'>,
                          <cfqueryparam value='#BR_BeginZoneID#' cfsqltype="cf_sql_integer" null='#IIF(exceldata.BR_BeginZoneID   EQ "", true, false)#'>,
                          <cfqueryparam value='#BR_EndZoneID#' cfsqltype="cf_sql_integer" null='#IIF(exceldata.BR_EndZoneID   EQ "", true, false)#'>,
                          <cfqueryparam value='#IR_BeginZoneID#' cfsqltype="cf_sql_integer" null='#IIF(exceldata.IR_BeginZoneID   EQ "", true, false)#'>,
                          <cfqueryparam value='#IR_EndZoneID#' cfsqltype="cf_sql_integer" null='#IIF(exceldata.IR_EndZoneID   EQ "", true, false)#'>,
                          <cfqueryparam value='#ML_BeginZoneID#' cfsqltype="cf_sql_integer" null='#IIF(exceldata.ML_BeginZoneID   EQ "", true, false)#'>,
                          <cfqueryparam value='#ML_EndZoneID#' cfsqltype="cf_sql_integer" null='#IIF(exceldata.ML_EndZoneID   EQ "", true, false)#'>,
                          <cfqueryparam value='#SLP_BeginZoneID#' cfsqltype="cf_sql_integer" null='#IIF(exceldata.SLP_BeginZoneID   EQ "", true, false)#'>,
                          <cfqueryparam value='#SLP_EndZoneID#' cfsqltype="cf_sql_integer" null='#IIF(exceldata.SLP_EndZoneID   EQ "", true, false)#'>,
                          <cfqueryparam value='#ATL_BeginZoneID#' cfsqltype="cf_sql_integer" null='#IIF(exceldata.ATL_BeginZoneID   EQ "", true, false)#'>,
                          <cfqueryparam value='#ATL_EndZoneID#' cfsqltype="cf_sql_integer" null='#IIF(exceldata.ATL_EndZoneID   EQ "", true, false)#'>,
                          <cfqueryparam value='#EnteredBy#' cfsqltype="cf_sql_varchar" null='#IIF(exceldata.EnteredBy   EQ "", true, false)#'>,
                          <cfqueryparam value='#Stock#' cfsqltype="cf_sql_varchar" null='#IIF(exceldata.Stock   EQ "", true, false)#'>,
                          <cfqueryparam value='#Summary#' cfsqltype="cf_sql_varchar" null='#IIF(exceldata.Summary   EQ "", true, false)#'>,
                          <cfqueryparam value='#SubType#' cfsqltype="cf_sql_varchar" null='#IIF(exceldata.SubType   EQ "", true, false)#'>,
                          <cfqueryparam value='#Type#' cfsqltype="cf_sql_varchar" null='#IIF(exceldata.Type   EQ "", true, false)#'>,
                          <cfqueryparam value='#Route#' cfsqltype="cf_sql_varchar" null='#IIF(exceldata.Route   EQ "", true, false)#'>,
                          <cfqueryparam value='#tempntbid#' cfsqltype="cf_sql_varchar" null='#IIF(exceldata.tempntbid   EQ "", true, false)#'>
                        )
                  </cfquery>
                <cfelseif isdefined("test_BIOPSY_SHOTS")>
                   <cfquery name="qru"  datasource="#Application.dsn#" result="insert">
                       insert into test_BIOPSY_SHOTS(
                         Sighting_ID,Dolphin_ID,ShotNumber,Hit,Miss,Sample,SampleNumber,Enter_Date,ShotTime,
                         Arbalester,TargetAnimalBehavior,ShotDistance,TargetLevel,TABPre_Activity_Mill,
                         TABPre_Activity_Feed,TABPre_Activity_ProbFeed,TABPre_Activity_Travel,TABPre_Activity_Play,
                         TABPre_ACTIVITY_REST,TABPre_Activity_Leap_tailslap_chuff,TABPre_Activity_Social,TABPre_ACTIVITY_WITHBOAT,
                         TABPre_Activity_Other,TABPre_Activity_Avoid_Boat,TABPre_Depredation,TABPre_Herding,TABPost_Activity_Mill,
                         TABPost_Activity_Feed,TABPost_Activity_ProbFeed,TABPost_Activity_Travel,TABPost_Activity_Play,
                         TABPost_ACTIVITY_REST,TABPost_Activity_Leap_tailslap_chuff,TABPost_Activity_Social,TABPost_ACTIVITY_WITHBOAT,
                         TABPost_Activity_Other,TABPost_Activity_Avoid_Boat,TABPost_Herding,GBPre_Activity_Mill,GBPre_Activity_Feed,
                         GBPre_Activity_ProbFeed,GBPre_Activity_Travel,GBPre_Activity_Play,GBPre_ACTIVITY_REST,GBPre_Activity_Leap_tailslap_chuff,
                         GBPre_Activity_Social,GBPre_ACTIVITY_WITHBOAT,GBPre_Activity_Other,GBPre_Activity_Avoid_Boat,GBPre_Depredation,
                         GBPre_Herding,GBPost_Activity_Mill,GBPost_Activity_Feed,GBPost_Activity_ProbFeed,GBPost_Activity_Travel,
                         GBPost_Activity_Play,GBPost_ACTIVITY_REST,GBPost_Activity_Leap_tailslap_chuff,GBPost_Activity_Social,GBPost_ACTIVITY_WITHBOAT,
                         GBPost_Activity_Other,GBPost_Activity_Avoid_Boat,GBPost_Depredation,GBPost_Herding,HitLocation,SubSample,
                         Processor,SampleLength,TABPost_Depredation,TargetResponseBehavior1,TargetResponseBehavior2,TargetResponseBehavior3,
                         GroupResponseBehavior,GroupSize,MissDistance,MissHeight,MissWidth,HitDescriptor,MissDescriptor,Samplehead,SampleCollected,
                         BlubberTeflonVial,BlubberCryovialRed,BlubberCryovialBlue,SkinDMSO,SkinRNAlater,SkinDCryovial,SampleTaken,Outcome,
                         TABPre_Activity_Mill2,TABPre_Activity_Feed2,TABPre_Activity_ProbFeed2,TABPre_Activity_Travel2,TABPre_Activity_Play2,
                         TABPre_ACTIVITY_REST2,TABPre_Activity_Leap_tailslap_chuff2,TABPre_Activity_Social2,TABPre_ACTIVITY_WITHBOAT2,
                         TABPre_Activity_Other2,TABPre_Activity_Avoid_Boat2,TABPre_Depredation2,TABPre_Herding2,TABPre_Activity_Mill3,
                         TABPre_Activity_Feed3,TABPre_Activity_ProbFeed3,TABPre_Activity_Travel3,TABPre_Activity_Play3,TABPre_ACTIVITY_REST3,
                         TABPre_Activity_Leap_tailslap_chuff3,TABPre_Activity_Social3,TABPre_ACTIVITY_WITHBOAT3,TABPre_Activity_Other3,
                         TABPre_Activity_Avoid_Boat3,TABPre_Depredation3,TABPre_Herding3,TABPost_Activity_Mill2,TABPost_Activity_Feed2,
                         TABPost_Activity_ProbFeed2,TABPost_Activity_Travel2,TABPost_Activity_Play2,TABPost_ACTIVITY_REST2,TABPost_Activity_Leap_tailslap_chuff2,
                         TABPost_Activity_Social2,TABPost_ACTIVITY_WITHBOAT2,TABPost_Activity_Other2,TABPost_Activity_Avoid_Boat2,
                         TABPost_Depredation2,TABPost_Herding2,TABPost_Activity_Mill3,TABPost_Activity_Feed3,TABPost_Activity_ProbFeed3,
                         TABPost_Activity_Travel3,TABPost_Activity_Play3,TABPost_ACTIVITY_REST3,TABPost_Activity_Leap_tailslap_chuff3,
                         TABPost_Activity_Social3,TABPost_ACTIVITY_WITHBOAT3,TABPost_Activity_Other3,TABPost_Activity_Avoid_Boat3,
                         TABPost_Depredation3,TABPost_Herding3,GBPre_Activity_Mill2,GBPre_Activity_Feed2,GBPre_Activity_ProbFeed2,
                         GBPre_Activity_Travel2,GBPre_Activity_Play2,GBPre_ACTIVITY_REST2,GBPre_Activity_Leap_tailslap_chuff2,GBPre_Activity_Social2,
                         GBPre_ACTIVITY_WITHBOAT2,GBPre_Activity_Other2,GBPre_Activity_Avoid_Boat2,GBPre_Depredation2,GBPre_Herding2,GBPre_Activity_Mill3,
                         GBPre_Activity_Feed3,GBPre_Activity_ProbFeed3,GBPre_Activity_Travel3,GBPre_Activity_Play3,GBPre_ACTIVITY_REST3,
                         GBPre_Activity_Leap_tailslap_chuff3,GBPre_Activity_Social3,GBPre_ACTIVITY_WITHBOAT3,GBPre_Activity_Other3,
                         GBPre_Activity_Avoid_Boat3,GBPre_Depredation3,GBPre_Herding3,GBPost_Activity_Mill2,GBPost_Activity_Feed2,
                         GBPost_Activity_ProbFeed2,GBPost_Activity_Travel2,GBPost_Activity_Play2,GBPost_ACTIVITY_REST2,
                         GBPost_Activity_Leap_tailslap_chuff2,GBPost_Activity_Social2,GBPost_ACTIVITY_WITHBOAT2,GBPost_Activity_Other2,
                         GBPost_Activity_Avoid_Boat2,GBPost_Depredation2,GBPost_Herding2,GBPost_Activity_Mill3,GBPost_Activity_Feed3,
                         GBPost_Activity_ProbFeed3,GBPost_Activity_Travel3,GBPost_Activity_Play3,GBPost_ACTIVITY_REST3,GBPost_Activity_Leap_tailslap_chuff3,
                         GBPost_Activity_Social3,GBPost_ACTIVITY_WITHBOAT3,GBPost_Activity_Other3,GBPost_Activity_Avoid_Boat3,GBPost_Depredation3,
                         GBPost_Herding3,TargetPre_Behavior1,TargetPre_Behavior2,TargetPre_Behavior3,TargetPost_Behavior1,TargetPost_Behavior2,
                         TargetPost_Behavior3,GroupPre_Behavior1,GroupPre_Behavior2,GroupPre_Behavior3,GroupPost_Behavior1,GroupPost_Behavior2,
                         GroupPost_Behavior3,TargetLevel2,TargetLevel3,GroupResponseBehavior2,GroupResponseBehavior3,GroupLevel1,probable_dolphin,
                         ShotCount
                        )
                       values(
                       <cfqueryparam cfsqltype="cf_sql_integer" value='#exceldata.Sighting_ID#'>,
                       <cfqueryparam cfsqltype="cf_sql_integer" value='#exceldata.Dolphin_ID#'>,
                       <cfqueryparam cfsqltype="cf_sql_varchar" value='#exceldata.ShotNumber#' null="#IIF(exceldata.ShotNumber EQ "", true, false)#">,
                       <cfqueryparam cfsqltype="cf_sql_bit" value='#exceldata.Hit#' null="#IIF(exceldata.Hit EQ "", true, false)#">,
                       <cfqueryparam cfsqltype="cf_sql_bit" value='#exceldata.Miss#' null="#IIF(exceldata.Miss EQ "", true, false)#">,
                       <cfqueryparam cfsqltype="cf_sql_varchar" value='#exceldata.Sample#' null="#IIF(exceldata.Sample EQ "", true, false)#">,
                       <cfqueryparam cfsqltype="cf_sql_varchar" value='#exceldata.SampleNumber#' null="#IIF(exceldata.SampleNumber EQ "", true, false)#">,
                       <cfqueryparam cfsqltype="cf_sql_timestamp" value='#exceldata.Enter_Date#' null="#IIF(exceldata.Enter_Date EQ "", true, false)#">,
                       <cfqueryparam cfsqltype="cf_sql_timestamp" value='#exceldata.ShotTime#' null="#IIF(exceldata.ShotTime EQ "", true, false)#">,
                       <cfqueryparam cfsqltype="cf_sql_varchar" value='#exceldata.Arbalester#' null="#IIF(exceldata.Arbalester EQ "", true, false)#">,
                       <cfqueryparam cfsqltype="cf_sql_integer" value='#exceldata.TargetAnimalBehavior#' null="#IIF(exceldata.TargetAnimalBehavior EQ "", true, false)#">,
                       <cfqueryparam cfsqltype="cf_sql_varchar" value='#exceldata.ShotDistance#' null="#IIF(exceldata.ShotDistance EQ "", true, false)#">,
                       <cfqueryparam cfsqltype="cf_sql_varchar" value='#exceldata.TargetLevel#' null="#IIF(exceldata.TargetLevel EQ "", true, false)#">,
                       <cfqueryparam cfsqltype="cf_sql_integer" value='#exceldata.TABPre_Activity_Mill#' null="#IIF(exceldata.TABPre_Activity_Mill EQ "", true, false)#">,
                       <cfqueryparam cfsqltype="cf_sql_integer" value='#exceldata.TABPre_Activity_Feed#' null="#IIF(exceldata.TABPre_Activity_Feed EQ "", true, false)#">,
                       <cfqueryparam cfsqltype="cf_sql_integer" value='#exceldata.TABPre_Activity_ProbFeed#' null="#IIF(exceldata.TABPre_Activity_ProbFeed EQ "", true, false)#">,
                       <cfqueryparam cfsqltype="cf_sql_integer" value='#exceldata.TABPre_Activity_Travel#' null="#IIF(exceldata.TABPre_Activity_Travel EQ "", true, false)#">,
                       <cfqueryparam cfsqltype="cf_sql_integer" value='#exceldata.TABPre_Activity_Play#' null="#IIF(exceldata.TABPre_Activity_Play EQ "", true, false)#">,
                       <cfqueryparam cfsqltype="cf_sql_integer" value='#exceldata.TABPre_ACTIVITY_REST#' null="#IIF(exceldata.TABPre_ACTIVITY_REST EQ "", true, false)#">,
                       <cfqueryparam cfsqltype="cf_sql_integer" value='#exceldata.TABPre_Activity_Leap_tailslap_chuff#' null="#IIF(exceldata.TABPre_Activity_Leap_tailslap_chuff EQ "", true, false)#">,
                       <cfqueryparam cfsqltype="cf_sql_integer" value='#exceldata.TABPre_Activity_Social#' null="#IIF(exceldata.TABPre_Activity_Social EQ "", true, false)#">,
                       <cfqueryparam cfsqltype="cf_sql_integer" value='#exceldata.TABPre_ACTIVITY_WITHBOAT#' null="#IIF(exceldata.TABPre_ACTIVITY_WITHBOAT EQ "", true, false)#">,
                       <cfqueryparam cfsqltype="cf_sql_integer" value='#exceldata.TABPre_Activity_Other#' null="#IIF(exceldata.TABPre_Activity_Other EQ "", true, false)#">,
                       <cfqueryparam cfsqltype="cf_sql_integer" value='#exceldata.TABPre_Activity_Avoid_Boat#' null="#IIF(exceldata.TABPre_Activity_Avoid_Boat EQ "", true, false)#">,
                       <cfqueryparam cfsqltype="cf_sql_integer" value='#exceldata.TABPre_Depredation#' null="#IIF(exceldata.TABPre_Depredation EQ "", true, false)#">,
                       <cfqueryparam cfsqltype="cf_sql_integer" value='#exceldata.TABPre_Herding#' null="#IIF(exceldata.TABPre_Herding EQ "", true, false)#">,
                       <cfqueryparam cfsqltype="cf_sql_integer" value='#exceldata.TABPost_Activity_Mill#' null="#IIF(exceldata.TABPost_Activity_Mill EQ "", true, false)#">,
                       <cfqueryparam cfsqltype="cf_sql_integer" value='#exceldata.TABPost_Activity_Feed#' null="#IIF(exceldata.TABPost_Activity_Feed EQ "", true, false)#">,
                       <cfqueryparam cfsqltype="cf_sql_integer" value='#exceldata.TABPost_Activity_ProbFeed#' null="#IIF(exceldata.TABPost_Activity_ProbFeed EQ "", true, false)#">,
                       <cfqueryparam cfsqltype="cf_sql_integer" value='#exceldata.TABPost_Activity_Travel#' null="#IIF(exceldata.TABPost_Activity_Travel EQ "", true, false)#">,
                       <cfqueryparam cfsqltype="cf_sql_integer" value='#exceldata.TABPost_Activity_Play#' null="#IIF(exceldata.TABPost_Activity_Play EQ "", true, false)#">,
                       <cfqueryparam cfsqltype="cf_sql_integer" value='#exceldata.TABPost_ACTIVITY_REST#' null="#IIF(exceldata.TABPost_ACTIVITY_REST EQ "", true, false)#">,
                       <cfqueryparam cfsqltype="cf_sql_integer" value='#exceldata.TABPost_Activity_Leap_tailslap_chuff#' null="#IIF(exceldata.TABPost_Activity_Leap_tailslap_chuff EQ "", true, false)#">,
                       <cfqueryparam cfsqltype="cf_sql_integer" value='#exceldata.TABPost_Activity_Social#' null="#IIF(exceldata.TABPost_Activity_Social EQ "", true, false)#">,
                       <cfqueryparam cfsqltype="cf_sql_integer" value='#exceldata.TABPost_ACTIVITY_WITHBOAT#' null="#IIF(exceldata.TABPost_ACTIVITY_WITHBOAT EQ "", true, false)#">,
                       <cfqueryparam cfsqltype="cf_sql_integer" value='#exceldata.TABPost_Activity_Other#' null="#IIF(exceldata.TABPost_Activity_Other EQ "", true, false)#">,
                       <cfqueryparam cfsqltype="cf_sql_integer" value='#exceldata.TABPost_Activity_Avoid_Boat#' null="#IIF(exceldata.TABPost_Activity_Avoid_Boat EQ "", true, false)#">,
                       <cfqueryparam cfsqltype="cf_sql_integer" value='#exceldata.TABPost_Herding#' null="#IIF(exceldata.TABPost_Herding EQ "", true, false)#">,
                       <cfqueryparam cfsqltype="cf_sql_integer" value='#exceldata.GBPre_Activity_Mill#' null="#IIF(exceldata.GBPre_Activity_Mill EQ "", true, false)#">,
                       <cfqueryparam cfsqltype="cf_sql_integer" value='#exceldata.GBPre_Activity_Feed#' null="#IIF(exceldata.GBPre_Activity_Feed EQ "", true, false)#">,
                       <cfqueryparam cfsqltype="cf_sql_integer" value='#exceldata.GBPre_Activity_ProbFeed#' null="#IIF(exceldata.GBPre_Activity_ProbFeed EQ "", true, false)#">,
                       <cfqueryparam cfsqltype="cf_sql_integer" value='#exceldata.GBPre_Activity_Travel#' null="#IIF(exceldata.GBPre_Activity_Travel EQ "", true, false)#">,
                       <cfqueryparam cfsqltype="cf_sql_integer" value='#exceldata.GBPre_Activity_Play#' null="#IIF(exceldata.GBPre_Activity_Play EQ "", true, false)#">,
                       <cfqueryparam cfsqltype="cf_sql_integer" value='#exceldata.GBPre_ACTIVITY_REST#' null="#IIF(exceldata.GBPre_ACTIVITY_REST EQ "", true, false)#">,
                       <cfqueryparam cfsqltype="cf_sql_integer" value='#exceldata.GBPre_Activity_Leap_tailslap_chuff#' null="#IIF(exceldata.GBPre_Activity_Leap_tailslap_chuff EQ "", true, false)#">,
                       <cfqueryparam cfsqltype="cf_sql_integer" value='#exceldata.GBPre_Activity_Social#' null="#IIF(exceldata.GBPre_Activity_Social EQ "", true, false)#">,
                       <cfqueryparam cfsqltype="cf_sql_integer" value='#exceldata.GBPre_ACTIVITY_WITHBOAT#' null="#IIF(exceldata.GBPre_ACTIVITY_WITHBOAT EQ "", true, false)#">,
                       <cfqueryparam cfsqltype="cf_sql_integer" value='#exceldata.GBPre_Activity_Other#' null="#IIF(exceldata.GBPre_Activity_Other EQ "", true, false)#">,
                       <cfqueryparam cfsqltype="cf_sql_integer" value='#exceldata.GBPre_Activity_Avoid_Boat#' null="#IIF(exceldata.GBPre_Activity_Avoid_Boat EQ "", true, false)#">,
                       <cfqueryparam cfsqltype="cf_sql_integer" value='#exceldata.GBPre_Depredation#' null="#IIF(exceldata.GBPre_Depredation EQ "", true, false)#">,
                       <cfqueryparam cfsqltype="cf_sql_integer" value='#exceldata.GBPre_Herding#' null="#IIF(exceldata.GBPre_Herding EQ "", true, false)#">,
                       <cfqueryparam cfsqltype="cf_sql_integer" value='#exceldata.GBPost_Activity_Mill#' null="#IIF(exceldata.GBPost_Activity_Mill EQ "", true, false)#">,
                       <cfqueryparam cfsqltype="cf_sql_integer" value='#exceldata.GBPost_Activity_Feed#' null="#IIF(exceldata.GBPost_Activity_Feed EQ "", true, false)#">,
                       <cfqueryparam cfsqltype="cf_sql_integer" value='#exceldata.GBPost_Activity_ProbFeed#' null="#IIF(exceldata.GBPost_Activity_ProbFeed EQ "", true, false)#">,
                       <cfqueryparam cfsqltype="cf_sql_integer" value='#exceldata.GBPost_Activity_Travel#' null="#IIF(exceldata.GBPost_Activity_Travel EQ "", true, false)#">,
                       <cfqueryparam cfsqltype="cf_sql_integer" value='#exceldata.GBPost_Activity_Play#' null="#IIF(exceldata.GBPost_Activity_Play EQ "", true, false)#">,
                       <cfqueryparam cfsqltype="cf_sql_integer" value='#exceldata.GBPost_ACTIVITY_REST#' null="#IIF(exceldata.GBPost_ACTIVITY_REST EQ "", true, false)#">,
                       <cfqueryparam cfsqltype="cf_sql_integer" value='#exceldata.GBPost_Activity_Leap_tailslap_chuff#' null="#IIF(exceldata.GBPost_Activity_Leap_tailslap_chuff EQ "", true, false)#">,
                       <cfqueryparam cfsqltype="cf_sql_integer" value='#exceldata.GBPost_Activity_Social#' null="#IIF(exceldata.GBPost_Activity_Social EQ "", true, false)#">,
                       <cfqueryparam cfsqltype="cf_sql_integer" value='#exceldata.GBPost_ACTIVITY_WITHBOAT#' null="#IIF(exceldata.GBPost_ACTIVITY_WITHBOAT EQ "", true, false)#">,
                       <cfqueryparam cfsqltype="cf_sql_integer" value='#exceldata.GBPost_Activity_Other#' null="#IIF(exceldata.GBPost_Activity_Other EQ "", true, false)#">,
                       <cfqueryparam cfsqltype="cf_sql_integer" value='#exceldata.GBPost_Activity_Avoid_Boat#' null="#IIF(exceldata.GBPost_Activity_Avoid_Boat EQ "", true, false)#">,
                       <cfqueryparam cfsqltype="cf_sql_integer" value='#exceldata.GBPost_Depredation#' null="#IIF(exceldata.GBPost_Depredation EQ "", true, false)#">,
                       <cfqueryparam cfsqltype="cf_sql_integer" value='#exceldata.GBPost_Herding#' null="#IIF(exceldata.GBPost_Herding EQ "", true, false)#">,
                       <cfqueryparam cfsqltype="cf_sql_integer" value='#exceldata.HitLocation#' null="#IIF(exceldata.HitLocation EQ "", true, false)#">,
                       <cfqueryparam cfsqltype="cf_sql_integer" value='#exceldata.SubSample#' null="#IIF(exceldata.SubSample EQ "", true, false)#">,
                       <cfqueryparam cfsqltype="cf_sql_varchar" value='#exceldata.Processor#' null="#IIF(exceldata.Processor EQ "", true, false)#">,
                       <cfqueryparam cfsqltype="cf_sql_varchar" value='#exceldata.SampleLength#' null="#IIF(exceldata.SampleLength EQ "", true, false)#">,
                       <cfqueryparam cfsqltype="cf_sql_integer" value='#exceldata.TABPost_Depredation#' null="#IIF(exceldata.TABPost_Depredation EQ "", true, false)#">,
                       <cfqueryparam cfsqltype="cf_sql_varchar" value='#exceldata.TargetResponseBehavior1#' null="#IIF(exceldata.TargetResponseBehavior1 EQ "", true, false)#">,
                       <cfqueryparam cfsqltype="cf_sql_varchar" value='#exceldata.TargetResponseBehavior2#' null="#IIF(exceldata.TargetResponseBehavior2 EQ "", true, false)#">,
                       <cfqueryparam cfsqltype="cf_sql_varchar" value='#exceldata.TargetResponseBehavior3#' null="#IIF(exceldata.TargetResponseBehavior3 EQ "", true, false)#">,
                       <cfqueryparam cfsqltype="cf_sql_varchar" value='#exceldata.GroupResponseBehavior#' null="#IIF(exceldata.GroupResponseBehavior EQ "", true, false)#">,
                       <cfqueryparam cfsqltype="cf_sql_varchar" value='#exceldata.GroupSize#' null="#IIF(exceldata.GroupSize EQ "", true, false)#">,
                       <cfqueryparam cfsqltype="cf_sql_varchar" value='#exceldata.MissDistance#' null="#IIF(exceldata.MissDistance EQ "", true, false)#">,
                       <cfqueryparam cfsqltype="cf_sql_varchar" value='#exceldata.MissHeight#' null="#IIF(exceldata.MissHeight EQ "", true, false)#">,
                       <cfqueryparam cfsqltype="cf_sql_varchar" value='#exceldata.MissWidth#' null="#IIF(exceldata.MissWidth EQ "", true, false)#">,
                       <cfqueryparam cfsqltype="cf_sql_varchar" value='#exceldata.HitDescriptor#' null="#IIF(exceldata.HitDescriptor EQ "", true, false)#">,
                       <cfqueryparam cfsqltype="cf_sql_varchar" value='#exceldata.MissDescriptor#' null="#IIF(exceldata.MissDescriptor EQ "", true, false)#">,
                       <cfqueryparam cfsqltype="cf_sql_integer" value='#exceldata.Samplehead#' null="#IIF(exceldata.Samplehead EQ "", true, false)#">,
                       <cfqueryparam cfsqltype="cf_sql_integer" value='#exceldata.SampleCollected#' null="#IIF(exceldata.SampleCollected EQ "", true, false)#">,
                       <cfqueryparam cfsqltype="cf_sql_integer" value='#exceldata.BlubberTeflonVial#' null="#IIF(exceldata.BlubberTeflonVial EQ "", true, false)#">,
                       <cfqueryparam cfsqltype="cf_sql_integer" value='#exceldata.BlubberCryovialRed#' null="#IIF(exceldata.BlubberCryovialRed EQ "", true, false)#">,
                       <cfqueryparam cfsqltype="cf_sql_integer" value='#exceldata.BlubberCryovialBlue#' null="#IIF(exceldata.BlubberCryovialBlue EQ "", true, false)#">,
                       <cfqueryparam cfsqltype="cf_sql_integer" value='#exceldata.SkinDMSO#' null="#IIF(exceldata.SkinDMSO EQ "", true, false)#">,
                       <cfqueryparam cfsqltype="cf_sql_integer" value='#exceldata.SkinRNAlater#' null="#IIF(exceldata.SkinRNAlater EQ "", true, false)#">,
                       <cfqueryparam cfsqltype="cf_sql_integer" value='#exceldata.SkinDCryovial#' null="#IIF(exceldata.SkinDCryovial EQ "", true, false)#">,
                       <cfqueryparam cfsqltype="cf_sql_integer" value='#exceldata.SampleTaken#' null="#IIF(exceldata.SampleTaken EQ "", true, false)#">,
                       <cfqueryparam cfsqltype="cf_sql_integer" value='#exceldata.Outcome#' null="#IIF(exceldata.Outcome EQ "", true, false)#">,
                       <cfqueryparam cfsqltype="cf_sql_integer" value='#exceldata.TABPre_Activity_Mill2#' null="#IIF(exceldata.TABPre_Activity_Mill2 EQ "", true, false)#">,
                       <cfqueryparam cfsqltype="cf_sql_integer" value='#exceldata.TABPre_Activity_Feed2#' null="#IIF(exceldata.TABPre_Activity_Feed2 EQ "", true, false)#">,
                       <cfqueryparam cfsqltype="cf_sql_integer" value='#exceldata.TABPre_Activity_ProbFeed2#' null="#IIF(exceldata.TABPre_Activity_ProbFeed2 EQ "", true, false)#">,
                       <cfqueryparam cfsqltype="cf_sql_integer" value='#exceldata.TABPre_Activity_Travel2#' null="#IIF(exceldata.TABPre_Activity_Travel2 EQ "", true, false)#">,
                       <cfqueryparam cfsqltype="cf_sql_integer" value='#exceldata.TABPre_Activity_Play2#' null="#IIF(exceldata.TABPre_Activity_Play2 EQ "", true, false)#">,
                       <cfqueryparam cfsqltype="cf_sql_integer" value='#exceldata.TABPre_ACTIVITY_REST2#' null="#IIF(exceldata.TABPre_ACTIVITY_REST2 EQ "", true, false)#">,
                       <cfqueryparam cfsqltype="cf_sql_integer" value='#exceldata.TABPre_Activity_Leap_tailslap_chuff2#' null="#IIF(exceldata.TABPre_Activity_Leap_tailslap_chuff2 EQ "", true, false)#">,
                       <cfqueryparam cfsqltype="cf_sql_integer" value='#exceldata.TABPre_Activity_Social2#' null="#IIF(exceldata.TABPre_Activity_Social2 EQ "", true, false)#">,
                       <cfqueryparam cfsqltype="cf_sql_integer" value='#exceldata.TABPre_ACTIVITY_WITHBOAT2#' null="#IIF(exceldata.TABPre_ACTIVITY_WITHBOAT2 EQ "", true, false)#">,
                       <cfqueryparam cfsqltype="cf_sql_integer" value='#exceldata.TABPre_Activity_Other2#' null="#IIF(exceldata.TABPre_Activity_Other2 EQ "", true, false)#">,
                       <cfqueryparam cfsqltype="cf_sql_integer" value='#exceldata.TABPre_Activity_Avoid_Boat2#' null="#IIF(exceldata.TABPre_Activity_Avoid_Boat2 EQ "", true, false)#">,
                       <cfqueryparam cfsqltype="cf_sql_integer" value='#exceldata.TABPre_Depredation2#' null="#IIF(exceldata.TABPre_Depredation2 EQ "", true, false)#">,
                       <cfqueryparam cfsqltype="cf_sql_integer" value='#exceldata.TABPre_Herding2#' null="#IIF(exceldata.TABPre_Herding2 EQ "", true, false)#">,
                       <cfqueryparam cfsqltype="cf_sql_integer" value='#exceldata.TABPre_Activity_Mill3#' null="#IIF(exceldata.TABPre_Activity_Mill3 EQ "", true, false)#">,
                       <cfqueryparam cfsqltype="cf_sql_integer" value='#exceldata.TABPre_Activity_Feed3#' null="#IIF(exceldata.TABPre_Activity_Feed3 EQ "", true, false)#">,
                       <cfqueryparam cfsqltype="cf_sql_integer" value='#exceldata.TABPre_Activity_ProbFeed3#' null="#IIF(exceldata.TABPre_Activity_ProbFeed3 EQ "", true, false)#">,
                       <cfqueryparam cfsqltype="cf_sql_integer" value='#exceldata.TABPre_Activity_Travel3#' null="#IIF(exceldata.TABPre_Activity_Travel3 EQ "", true, false)#">,
                       <cfqueryparam cfsqltype="cf_sql_integer" value='#exceldata.TABPre_Activity_Play3#' null="#IIF(exceldata.TABPre_Activity_Play3 EQ "", true, false)#">,
                       <cfqueryparam cfsqltype="cf_sql_integer" value='#exceldata.TABPre_ACTIVITY_REST3#' null="#IIF(exceldata.TABPre_ACTIVITY_REST3 EQ "", true, false)#">,
                       <cfqueryparam cfsqltype="cf_sql_integer" value='#exceldata.TABPre_Activity_Leap_tailslap_chuff3#' null="#IIF(exceldata.TABPre_Activity_Leap_tailslap_chuff3 EQ "", true, false)#">,
                       <cfqueryparam cfsqltype="cf_sql_integer" value='#exceldata.TABPre_Activity_Social3#' null="#IIF(exceldata.TABPre_Activity_Social3 EQ "", true, false)#">,
                       <cfqueryparam cfsqltype="cf_sql_integer" value='#exceldata.TABPre_ACTIVITY_WITHBOAT3#' null="#IIF(exceldata.TABPre_ACTIVITY_WITHBOAT3 EQ "", true, false)#">,
                       <cfqueryparam cfsqltype="cf_sql_integer" value='#exceldata.TABPre_Activity_Other3#' null="#IIF(exceldata.TABPre_Activity_Other3 EQ "", true, false)#">,
                       <cfqueryparam cfsqltype="cf_sql_integer" value='#exceldata.TABPre_Activity_Avoid_Boat3#' null="#IIF(exceldata.TABPre_Activity_Avoid_Boat3 EQ "", true, false)#">,
                       <cfqueryparam cfsqltype="cf_sql_integer" value='#exceldata.TABPre_Depredation3#' null="#IIF(exceldata.TABPre_Depredation3 EQ "", true, false)#">,
                       <cfqueryparam cfsqltype="cf_sql_integer" value='#exceldata.TABPre_Herding3#' null="#IIF(exceldata.TABPre_Herding3 EQ "", true, false)#">,
                       <cfqueryparam cfsqltype="cf_sql_integer" value='#exceldata.TABPost_Activity_Mill2#' null="#IIF(exceldata.TABPost_Activity_Mill2 EQ "", true, false)#">,
                       <cfqueryparam cfsqltype="cf_sql_integer" value='#exceldata.TABPost_Activity_Feed2#' null="#IIF(exceldata.TABPost_Activity_Feed2 EQ "", true, false)#">,
                       <cfqueryparam cfsqltype="cf_sql_integer" value='#exceldata.TABPost_Activity_ProbFeed2#' null="#IIF(exceldata.TABPost_Activity_ProbFeed2 EQ "", true, false)#">,
                       <cfqueryparam cfsqltype="cf_sql_integer" value='#exceldata.TABPost_Activity_Travel2#' null="#IIF(exceldata.TABPost_Activity_Travel2 EQ "", true, false)#">,
                       <cfqueryparam cfsqltype="cf_sql_integer" value='#exceldata.TABPost_Activity_Play2#' null="#IIF(exceldata.TABPost_Activity_Play2 EQ "", true, false)#">,
                       <cfqueryparam cfsqltype="cf_sql_integer" value='#exceldata.TABPost_ACTIVITY_REST2#' null="#IIF(exceldata.TABPost_ACTIVITY_REST2 EQ "", true, false)#">,
                       <cfqueryparam cfsqltype="cf_sql_integer" value='#exceldata.TABPost_Activity_Leap_tailslap_chuff2#' null="#IIF(exceldata.TABPost_Activity_Leap_tailslap_chuff2 EQ "", true, false)#">,
                       <cfqueryparam cfsqltype="cf_sql_integer" value='#exceldata.TABPost_Activity_Social2#' null="#IIF(exceldata.TABPost_Activity_Social2 EQ "", true, false)#">,
                       <cfqueryparam cfsqltype="cf_sql_integer" value='#exceldata.TABPost_ACTIVITY_WITHBOAT2#' null="#IIF(exceldata.TABPost_ACTIVITY_WITHBOAT2 EQ "", true, false)#">,
                       <cfqueryparam cfsqltype="cf_sql_integer" value='#exceldata.TABPost_Activity_Other2#' null="#IIF(exceldata.TABPost_Activity_Other2 EQ "", true, false)#">,
                       <cfqueryparam cfsqltype="cf_sql_integer" value='#exceldata.TABPost_Activity_Avoid_Boat2#' null="#IIF(exceldata.TABPost_Activity_Avoid_Boat2 EQ "", true, false)#">,
                       <cfqueryparam cfsqltype="cf_sql_integer" value='#exceldata.TABPost_Depredation2#' null="#IIF(exceldata.TABPost_Depredation2 EQ "", true, false)#">,
                       <cfqueryparam cfsqltype="cf_sql_integer" value='#exceldata.TABPost_Herding2#' null="#IIF(exceldata.TABPost_Herding2 EQ "", true, false)#">,
                       <cfqueryparam cfsqltype="cf_sql_integer" value='#exceldata.TABPost_Activity_Mill3#' null="#IIF(exceldata.TABPost_Activity_Mill3 EQ "", true, false)#">,
                       <cfqueryparam cfsqltype="cf_sql_integer" value='#exceldata.TABPost_Activity_Feed3#' null="#IIF(exceldata.TABPost_Activity_Feed3 EQ "", true, false)#">,
                       <cfqueryparam cfsqltype="cf_sql_integer" value='#exceldata.TABPost_Activity_ProbFeed3#' null="#IIF(exceldata.TABPost_Activity_ProbFeed3 EQ "", true, false)#">,
                       <cfqueryparam cfsqltype="cf_sql_integer" value='#exceldata.TABPost_Activity_Travel3#' null="#IIF(exceldata.TABPost_Activity_Travel3 EQ "", true, false)#">,
                       <cfqueryparam cfsqltype="cf_sql_integer" value='#exceldata.TABPost_Activity_Play3#' null="#IIF(exceldata.TABPost_Activity_Play3 EQ "", true, false)#">,
                       <cfqueryparam cfsqltype="cf_sql_integer" value='#exceldata.TABPost_ACTIVITY_REST3#' null="#IIF(exceldata.TABPost_ACTIVITY_REST3 EQ "", true, false)#">,
                       <cfqueryparam cfsqltype="cf_sql_integer" value='#exceldata.TABPost_Activity_Leap_tailslap_chuff3#' null="#IIF(exceldata.TABPost_Activity_Leap_tailslap_chuff3 EQ "", true, false)#">,
                       <cfqueryparam cfsqltype="cf_sql_integer" value='#exceldata.TABPost_Activity_Social3#' null="#IIF(exceldata.TABPost_Activity_Social3 EQ "", true, false)#">,
                       <cfqueryparam cfsqltype="cf_sql_integer" value='#exceldata.TABPost_ACTIVITY_WITHBOAT3#' null="#IIF(exceldata.TABPost_ACTIVITY_WITHBOAT3 EQ "", true, false)#">,
                       <cfqueryparam cfsqltype="cf_sql_integer" value='#exceldata.TABPost_Activity_Other3#' null="#IIF(exceldata.TABPost_Activity_Other3 EQ "", true, false)#">,
                       <cfqueryparam cfsqltype="cf_sql_integer" value='#exceldata.TABPost_Activity_Avoid_Boat3#' null="#IIF(exceldata.TABPost_Activity_Avoid_Boat3 EQ "", true, false)#">,
                       <cfqueryparam cfsqltype="cf_sql_integer" value='#exceldata.TABPost_Depredation3#' null="#IIF(exceldata.TABPost_Depredation3 EQ "", true, false)#">,
                       <cfqueryparam cfsqltype="cf_sql_integer" value='#exceldata.TABPost_Herding3#' null="#IIF(exceldata.TABPost_Herding3 EQ "", true, false)#">,
                       <cfqueryparam cfsqltype="cf_sql_integer" value='#exceldata.GBPre_Activity_Mill2#' null="#IIF(exceldata.GBPre_Activity_Mill2 EQ "", true, false)#">,
                       <cfqueryparam cfsqltype="cf_sql_integer" value='#exceldata.GBPre_Activity_Feed2#' null="#IIF(exceldata.GBPre_Activity_Feed2 EQ "", true, false)#">,
                       <cfqueryparam cfsqltype="cf_sql_integer" value='#exceldata.GBPre_Activity_ProbFeed2#' null="#IIF(exceldata.GBPre_Activity_ProbFeed2 EQ "", true, false)#">,
                       <cfqueryparam cfsqltype="cf_sql_integer" value='#exceldata.GBPre_Activity_Travel2#' null="#IIF(exceldata.GBPre_Activity_Travel2 EQ "", true, false)#">,
                       <cfqueryparam cfsqltype="cf_sql_integer" value='#exceldata.GBPre_Activity_Play2#' null="#IIF(exceldata.GBPre_Activity_Play2 EQ "", true, false)#">,
                       <cfqueryparam cfsqltype="cf_sql_integer" value='#exceldata.GBPre_ACTIVITY_REST2#' null="#IIF(exceldata.GBPre_ACTIVITY_REST2 EQ "", true, false)#">,
                       <cfqueryparam cfsqltype="cf_sql_integer" value='#exceldata.GBPre_Activity_Leap_tailslap_chuff2#' null="#IIF(exceldata.GBPre_Activity_Leap_tailslap_chuff2 EQ "", true, false)#">,
                       <cfqueryparam cfsqltype="cf_sql_integer" value='#exceldata.GBPre_Activity_Social2#' null="#IIF(exceldata.GBPre_Activity_Social2 EQ "", true, false)#">,
                       <cfqueryparam cfsqltype="cf_sql_integer" value='#exceldata.GBPre_ACTIVITY_WITHBOAT2#' null="#IIF(exceldata.GBPre_ACTIVITY_WITHBOAT2 EQ "", true, false)#">,
                       <cfqueryparam cfsqltype="cf_sql_integer" value='#exceldata.GBPre_Activity_Other2#' null="#IIF(exceldata.GBPre_Activity_Other2 EQ "", true, false)#">,
                       <cfqueryparam cfsqltype="cf_sql_integer" value='#exceldata.GBPre_Activity_Avoid_Boat2#' null="#IIF(exceldata.GBPre_Activity_Avoid_Boat2 EQ "", true, false)#">,
                       <cfqueryparam cfsqltype="cf_sql_integer" value='#exceldata.GBPre_Depredation2#' null="#IIF(exceldata.GBPre_Depredation2 EQ "", true, false)#">,
                       <cfqueryparam cfsqltype="cf_sql_integer" value='#exceldata.GBPre_Herding2#' null="#IIF(exceldata.GBPre_Herding2 EQ "", true, false)#">,
                       <cfqueryparam cfsqltype="cf_sql_integer" value='#exceldata.GBPre_Activity_Mill3#' null="#IIF(exceldata.GBPre_Activity_Mill3 EQ "", true, false)#">,
                       <cfqueryparam cfsqltype="cf_sql_integer" value='#exceldata.GBPre_Activity_Feed3#' null="#IIF(exceldata.GBPre_Activity_Feed3   EQ "", true, false)#">,
                       <cfqueryparam cfsqltype="cf_sql_integer" value='#exceldata.GBPre_Activity_ProbFeed3#' null="#IIF(exceldata.GBPre_Activity_ProbFeed3   EQ "", true, false)#">,
                       <cfqueryparam cfsqltype="cf_sql_integer" value='#exceldata.GBPre_Activity_Travel3#' null="#IIF(exceldata.GBPre_Activity_Travel3   EQ "", true, false)#">,
                       <cfqueryparam cfsqltype="cf_sql_integer" value='#exceldata.GBPre_Activity_Play3#' null="#IIF(exceldata.GBPre_Activity_Play3   EQ "", true, false)#">,
                       <cfqueryparam cfsqltype="cf_sql_integer" value='#exceldata.GBPre_ACTIVITY_REST3#' null="#IIF(exceldata.GBPre_ACTIVITY_REST3   EQ "", true, false)#">,
                       <cfqueryparam cfsqltype="cf_sql_integer" value='#exceldata.GBPre_Activity_Leap_tailslap_chuff3#' null="#IIF(exceldata.GBPre_Activity_Leap_tailslap_chuff3   EQ "", true, false)#">,
                       <cfqueryparam cfsqltype="cf_sql_integer" value='#exceldata.GBPre_Activity_Social3#' null="#IIF(exceldata.GBPre_Activity_Social3   EQ "", true, false)#">,
                       <cfqueryparam cfsqltype="cf_sql_integer" value='#exceldata.GBPre_ACTIVITY_WITHBOAT3#' null="#IIF(exceldata.GBPre_ACTIVITY_WITHBOAT3   EQ "", true, false)#">,
                       <cfqueryparam cfsqltype="cf_sql_integer" value='#exceldata.GBPre_Activity_Other3#' null="#IIF(exceldata.GBPre_Activity_Other3   EQ "", true, false)#">,
                       <cfqueryparam cfsqltype="cf_sql_integer" value='#exceldata.GBPre_Activity_Avoid_Boat3#' null="#IIF(exceldata.GBPre_Activity_Avoid_Boat3  EQ "", true, false)#">,
                       <cfqueryparam cfsqltype="cf_sql_integer" value='#exceldata.GBPre_Depredation3#' null="#IIF(exceldata.GBPre_Depredation3  EQ "", true, false)#">,
                       <cfqueryparam cfsqltype="cf_sql_integer" value='#exceldata.GBPre_Herding3#' null="#IIF(exceldata.GBPre_Herding3  EQ "", true, false)#">,
                       <cfqueryparam cfsqltype="cf_sql_integer" value='#exceldata.GBPost_Activity_Mill2#' null="#IIF(exceldata.GBPost_Activity_Mill2  EQ "", true, false)#">,
                       <cfqueryparam cfsqltype="cf_sql_integer" value='#exceldata.GBPost_Activity_Feed2#' null="#IIF(exceldata.GBPost_Activity_Feed2  EQ "", true, false)#">,
                       <cfqueryparam cfsqltype="cf_sql_integer" value='#exceldata.GBPost_Activity_ProbFeed2#' null="#IIF(exceldata.GBPost_Activity_ProbFeed2  EQ "", true, false)#">,
                       <cfqueryparam cfsqltype="cf_sql_integer" value='#exceldata.GBPost_Activity_Travel2#' null="#IIF(exceldata.GBPost_Activity_Travel2  EQ "", true, false)#">,
                       <cfqueryparam cfsqltype="cf_sql_integer" value='#exceldata.GBPost_Activity_Play2#' null="#IIF(exceldata.GBPost_Activity_Play2  EQ "", true, false)#">,
                       <cfqueryparam cfsqltype="cf_sql_integer" value='#exceldata.GBPost_ACTIVITY_REST2#' null="#IIF(exceldata.GBPost_ACTIVITY_REST2  EQ "", true, false)#">,
                       <cfqueryparam cfsqltype="cf_sql_integer" value='#exceldata.GBPost_Activity_Leap_tailslap_chuff2#' null="#IIF(exceldata.GBPost_Activity_Leap_tailslap_chuff2  EQ "", true, false)#">,
                       <cfqueryparam cfsqltype="cf_sql_integer" value='#exceldata.GBPost_Activity_Social2#' null="#IIF(exceldata.GBPost_Activity_Social2  EQ "", true, false)#">,
                       <cfqueryparam cfsqltype="cf_sql_integer" value='#exceldata.GBPost_ACTIVITY_WITHBOAT2#' null="#IIF(exceldata.GBPost_ACTIVITY_WITHBOAT2  EQ "", true, false)#">,
                       <cfqueryparam cfsqltype="cf_sql_integer" value='#exceldata.GBPost_Activity_Other2#' null="#IIF(exceldata.GBPost_Activity_Other2  EQ "", true, false)#">,
                       <cfqueryparam cfsqltype="cf_sql_integer" value='#exceldata.GBPost_Activity_Avoid_Boat2#' null="#IIF(exceldata.GBPost_Activity_Avoid_Boat2  EQ "", true, false)#">,
                       <cfqueryparam cfsqltype="cf_sql_integer" value='#exceldata.GBPost_Depredation2#' null="#IIF(exceldata.GBPost_Depredation2  EQ "", true, false)#">,
                       <cfqueryparam cfsqltype="cf_sql_integer" value='#exceldata.GBPost_Herding2#' null="#IIF(exceldata.GBPost_Herding2  EQ "", true, false)#">,
                       <cfqueryparam cfsqltype="cf_sql_integer" value='#exceldata.GBPost_Activity_Mill3#' null="#IIF(exceldata.GBPost_Activity_Mill3  EQ "", true, false)#">,
                       <cfqueryparam cfsqltype="cf_sql_integer" value='#exceldata.GBPost_Activity_Feed3#' null="#IIF(exceldata.GBPost_Activity_Feed3  EQ "", true, false)#">,
                       <cfqueryparam cfsqltype="cf_sql_integer" value='#exceldata.GBPost_Activity_ProbFeed3#' null="#IIF(exceldata.GBPost_Activity_ProbFeed3  EQ "", true, false)#">,
                       <cfqueryparam cfsqltype="cf_sql_integer" value='#exceldata.GBPost_Activity_Travel3#' null="#IIF(exceldata.GBPost_Activity_Travel3  EQ "", true, false)#">,
                       <cfqueryparam cfsqltype="cf_sql_integer" value='#exceldata.GBPost_Activity_Play3#' null="#IIF(exceldata.GBPost_Activity_Play3  EQ "", true, false)#">,
                       <cfqueryparam cfsqltype="cf_sql_integer" value='#exceldata.GBPost_ACTIVITY_REST3#' null="#IIF(exceldata.GBPost_ACTIVITY_REST3  EQ "", true, false)#">,
                       <cfqueryparam cfsqltype="cf_sql_integer" value='#exceldata.GBPost_Activity_Leap_tailslap_chuff3#' null="#IIF(exceldata.GBPost_Activity_Leap_tailslap_chuff3  EQ "", true, false)#">,
                       <cfqueryparam cfsqltype="cf_sql_integer" value='#exceldata.GBPost_Activity_Social3#' null="#IIF(exceldata.GBPost_Activity_Social3  EQ "", true, false)#">,
                       <cfqueryparam cfsqltype="cf_sql_integer" value='#exceldata.GBPost_ACTIVITY_WITHBOAT3#' null="#IIF(exceldata.GBPost_ACTIVITY_WITHBOAT3  EQ "", true, false)#">,
                       <cfqueryparam cfsqltype="cf_sql_integer" value='#exceldata.GBPost_Activity_Other3#' null="#IIF(exceldata.GBPost_Activity_Other3  EQ "", true, false)#">,
                       <cfqueryparam cfsqltype="cf_sql_integer" value='#exceldata.GBPost_Activity_Avoid_Boat3#' null="#IIF(exceldata.GBPost_Activity_Avoid_Boat3  EQ "", true, false)#">,
                       <cfqueryparam cfsqltype="cf_sql_integer" value='#exceldata.GBPost_Depredation3#' null="#IIF(exceldata.GBPost_Depredation3  EQ "", true, false)#">,
                       <cfqueryparam cfsqltype="cf_sql_integer" value='#exceldata.GBPost_Herding3#' null="#IIF(exceldata.GBPost_Herding3  EQ "", true, false)#">,
                       <cfqueryparam cfsqltype="cf_sql_varchar" value='#exceldata.TargetPre_Behavior1#' null="#IIF(exceldata.TargetPre_Behavior1  EQ "", true, false)#">,
                       <cfqueryparam cfsqltype="cf_sql_varchar" value='#exceldata.TargetPre_Behavior2#' null="#IIF(exceldata.TargetPre_Behavior2  EQ "", true, false)#">,
                       <cfqueryparam cfsqltype="cf_sql_varchar" value='#exceldata.TargetPre_Behavior3#' null="#IIF(exceldata.TargetPre_Behavior3  EQ "", true, false)#">,
                       <cfqueryparam cfsqltype="cf_sql_varchar" value='#exceldata.TargetPost_Behavior1#' null="#IIF(exceldata.TargetPost_Behavior1  EQ "", true, false)#">,
                       <cfqueryparam cfsqltype="cf_sql_varchar" value='#exceldata.TargetPost_Behavior2#' null="#IIF(exceldata.TargetPost_Behavior2  EQ "", true, false)#">,
                       <cfqueryparam cfsqltype="cf_sql_varchar" value='#exceldata.TargetPost_Behavior3#' null="#IIF(exceldata.TargetPost_Behavior3  EQ "", true, false)#">,
                       <cfqueryparam cfsqltype="cf_sql_varchar" value='#exceldata.GroupPre_Behavior1#' null="#IIF(exceldata.GroupPre_Behavior1  EQ "", true, false)#">,
                       <cfqueryparam cfsqltype="cf_sql_varchar" value='#exceldata.GroupPre_Behavior2#' null="#IIF(exceldata.GroupPre_Behavior2  EQ "", true, false)#">,
                       <cfqueryparam cfsqltype="cf_sql_varchar" value='#exceldata.GroupPre_Behavior3#' null="#IIF(exceldata.GroupPre_Behavior3  EQ "", true, false)#">,
                       <cfqueryparam cfsqltype="cf_sql_varchar" value='#exceldata.GroupPost_Behavior1#' null="#IIF(exceldata.GroupPost_Behavior1  EQ "", true, false)#">,
                       <cfqueryparam cfsqltype="cf_sql_varchar" value='#exceldata.GroupPost_Behavior2#' null="#IIF(exceldata.GroupPost_Behavior2  EQ "", true, false)#">,
                       <cfqueryparam cfsqltype="cf_sql_varchar" value='#exceldata.GroupPost_Behavior3#' null="#IIF(exceldata.GroupPost_Behavior3  EQ "", true, false)#">,
                       <cfqueryparam cfsqltype="cf_sql_varchar" value='#exceldata.TargetLevel2#' null="#IIF(exceldata.TargetLevel2  EQ "", true, false)#">,
                       <cfqueryparam cfsqltype="cf_sql_varchar" value='#exceldata.TargetLevel3#' null="#IIF(exceldata.TargetLevel3  EQ "", true, false)#">,
                        <cfqueryparam cfsqltype="cf_sql_varchar" value='#exceldata.GroupResponseBehavior2#' null="#IIF(exceldata.GroupResponseBehavior2  EQ "", true, false)#">,
                        <cfqueryparam cfsqltype="cf_sql_varchar" value='#exceldata.GroupResponseBehavior3#' null="#IIF(exceldata.GroupResponseBehavior3  EQ "", true, false)#">,
                        <cfqueryparam cfsqltype="cf_sql_varchar" value='#exceldata.GroupLevel1#' null="#IIF(exceldata.GroupLevel1  EQ "", true, false)#">,
                        <cfqueryparam cfsqltype="cf_sql_integer" value='#exceldata.probable_dolphin#' null="#IIF(exceldata.probable_dolphin  EQ "", true, false)#">,
                        <cfqueryparam cfsqltype="cf_sql_integer" value='#exceldata.ShotCount#' null="#IIF(exceldata.ShotCount  EQ "", true, false)#">
                       )
                          </cfquery>
                         </cfif>
                       <cfif #insert.recordcount# eq 1>
                     <cfset counter= 1>
                  </cfif>
            <!---<cfcatch type="any">--->
                <!---<cfoutput>--->
                    <!---<h2 style="text-align: center">Message: <b>#cfcatch.Message#</b></h2>--->
                <!---Error occured....<br /><br />--->
                <!---Message: <b>#cfcatch.Message#</b><br />--->
                <!---Detail:  <b>#cfcatch.Detail#</b><br />--->
                <!---Type:    <b>#cfcatch.Type#</b><br />--->
                <!---</cfoutput>--->
            <!---</cfcatch>--->
        <!---</cftry>--->
                    </cfloop>
                 </cfif>
              </cfif>

        <cfif counter eq 1>

          <cfoutput><h3 style="text-align: center"> data inserted Successfully !</h3></cfoutput>
         <cfelseif counter eq 2  >
            <cfoutput><h3 style="text-align: center">Error Occured ! Please check your file </h3></cfoutput>
         </cfif>



